CREATE OR REPLACE PACKAGE FIDE_KALO_PKG IS

    /*
        FUNCIONES DE LECTURA PARA EL SITIO WEB
        Basadas exclusivamente en las tablas definidas en scheme.sql
    */

    /* ============================================================
       CATALOGOS Y UBICACIONES
       ============================================================ */

    FUNCTION FIDE_OBTENER_ESTADOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_USUARIO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAISES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PROVINCIAS_POR_PAIS_FN(
        P_ID_PAIS IN FIDE_PROVINCIA_TB.ID_PAIS%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CANTONES_POR_PROVINCIA_FN(
        P_ID_PROVINCIA IN FIDE_CANTON_TB.ID_PROVINCIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DISTRITOS_POR_CANTON_FN(
        P_ID_CANTON IN FIDE_DISTRITO_TB.ID_CANTON%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_JERARQUIA_DISTRITO_FN(
        P_ID_PAIS      IN FIDE_PAIS_TB.ID_PAIS%TYPE,
        P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
        P_ID_CANTON    IN FIDE_CANTON_TB.ID_CANTON%TYPE,
        P_ID_DISTRITO  IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_OTP_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CATEGORIAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MARCAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_MOVIMIENTO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CAMPANIAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MONEDAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RAZAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEXOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_SOLICITUD_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_RESPUESTA_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_SEGUIMIENTO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_EVENTO_FN
    RETURN SYS_REFCURSOR;

    /* ============================================================
       USUARIOS Y AUTENTICACION
       ============================================================ */

    FUNCTION FIDE_OBTENER_DIRECCION_POR_ID_FN(
        P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_USUARIOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_USUARIO_POR_IDENTIFICACION_FN(
        P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CORREOS_USUARIO_FN(
        P_IDENTIFICACION IN FIDE_CORREO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CORREO_POR_DIRECCION_FN(
        P_CORREO IN FIDE_CORREO_TB.CORREO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TELEFONOS_USUARIO_FN(
        P_IDENTIFICACION IN FIDE_TELEFONO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TELEFONO_POR_NUMERO_FN(
        P_TELEFONO IN FIDE_TELEFONO_TB.TELEFONO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CUENTA_POR_CORREO_FN(
        P_USUARIO IN FIDE_CUENTA_TB.USUARIO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CUENTA_POR_ID_CUENTA_FN(
        P_ID_CUENTA IN FIDE_CUENTA_TB.ID_CUENTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CUENTA_POR_IDENTIFICACION_FN(
        P_IDENTIFICACION IN FIDE_CUENTA_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_OTPS_ACTIVOS_POR_CUENTA_FN(
        P_ID_CUENTA   IN FIDE_CODIGO_OTP_TB.ID_CUENTA%TYPE,
        P_ID_TIPO_OTP IN FIDE_CODIGO_OTP_TB.ID_TIPO_OTP%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_REFRESH_TOKENS_POR_CUENTA_FN(
        P_ID_CUENTA IN FIDE_REFRESH_TOKEN_TB.ID_CUENTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_VERIFICAR_PERMISO_ADMIN_FN(
        P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       TIENDA, PRODUCTOS E INVENTARIO
       ============================================================ */

    FUNCTION FIDE_OBTENER_PRODUCTOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PRODUCTO_POR_ID_FN(
        P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_INVENTARIO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MOVIMIENTOS_INVENTARIO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MOVIMIENTOS_PRODUCTO_FN(
        P_ID_PRODUCTO IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_PRODUCTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_VERIFICAR_STOCK_TIENDA_FN(
        P_ID_PRODUCTO          IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
        P_CANTIDAD_REQUERIDA   IN NUMBER
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       PREGUNTAS, SOLICITUDES Y CASAS CUNA
       ============================================================ */

    FUNCTION FIDE_OBTENER_PREGUNTAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SOLICITUDES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SOLICITUD_POR_ID_FN(
        P_ID_SOLICITUD IN FIDE_SOLICITUD_TB.ID_SOLICITUD%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RESPUESTAS_POR_SOLICITUD_FN(
        P_ID_SOLICITUD IN FIDE_RESPUESTA_TB.ID_SOLICITUD%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CASAS_CUNA_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_PERRITOS_EN_CASA_CUNA_FN(
        P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PERRITOS_CASA_CUNA_FN(
        P_ID_CASA_CUNA IN FIDE_CASA_PERRITO_TB.ID_CASA_CUNA%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       PERRITOS Y EVENTOS
       ============================================================ */

    FUNCTION FIDE_OBTENER_PERRO_DISPONIBLES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PERRO_POR_ID_FN(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_IMAGENES_PERRO_FN(
        P_ID_PERRITO IN FIDE_PERRITO_IMAGE_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_HISTORIAL_MEDICO_PERRITO_FN(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DETALLES_EVENTO_FN(
        P_ID_EVENTO IN FIDE_DETALLE_EVENTO_TB.ID_EVENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_GASTOS_POR_PERRO_FN(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_BUSCAR_PERROS_FILTROS_FN(
        P_EDAD_MAX IN NUMBER,
        P_PESO_MAX IN NUMBER,
        P_ID_SEXO  IN NUMBER
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_CALCULAR_DIAS_ALBERGUE_FN(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       DONACIONES, VENTAS Y FACTURACION
       ============================================================ */

    FUNCTION FIDE_OBTENER_DONACIONES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DONACIONES_POR_USUARIO_FN(
        P_IDENTIFICACION IN FIDE_DONACION_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DONACIONES_POR_CAMPANIA_FN(
        P_ID_CAMPANIA IN FIDE_DONACION_TB.ID_CAMPANIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_TOTAL_DONACIONES_MES_FN(
        P_MES  IN NUMBER,
        P_YEAR IN NUMBER
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_TOTAL_RECAUDADO_CAMPANIA_FN(
        P_ID_CAMPANIA IN FIDE_CAMPANIA_TB.ID_CAMPANIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_VENTAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DETALLE_VENTA_FN(
        P_ID_VENTA IN FIDE_VENTA_PRODUCTO_TB.ID_VENTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_FACTURAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_FACTURA_POR_ID_FN(
        P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_FACTURAS_VENTA_FN(
        P_ID_VENTA IN FIDE_VENTA_FACTURA_TB.ID_VENTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_FACTURAS_DONACION_FN(
        P_ID_DONACION IN FIDE_DONACION_FACTURA_TB.ID_DONACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAGOS_PAYPAL_POR_FACTURA_FN(
        P_ID_FACTURA IN FIDE_PAGO_PAYPAL_TB.ID_FACTURA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_BALANCE_FINANCIERO_MENSUAL_FN(
        P_MES  IN NUMBER,
        P_YEAR IN NUMBER
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       ADOPCIONES, SEGUIMIENTOS Y REPORTES
       ============================================================ */

    FUNCTION FIDE_ELEGIBILIDAD_ADOPTANTE_FN(
        P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_ADOPCIONES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_ESTADISTICAS_ADOPCION_ANUAL_FN(
        P_YEAR IN NUMBER
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEGUIMIENTOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEGUIMIENTOS_POR_ADOPCION_FN(
        P_ID_ADOPCION IN FIDE_SEGUIMIENTO_TB.ID_ADOPCION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_ALERTAS_SEGUIMIENTO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_EVIDENCIAS_POR_SEGUIMIENTO_FN(
        P_ID_SEGUIMIENTO IN FIDE_EVIDENCIA_TB.ID_SEGUIMIENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       FUNCIONES COMPLEMENTARIAS PARA CRUD ADMIN
       CATALOGOS Y UBICACIONES
       ============================================================ */

    FUNCTION FIDE_OBTENER_ESTADO_POR_ID_FN(
        P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_USUARIO_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_USUARIO_POR_ID_FN(
        P_ID_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.ID_TIPO_USUARIO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAIS_POR_ID_FN(
        P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAISES_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_OTP_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CATEGORIAS_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MARCAS_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MONEDAS_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RAZAS_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEXOS_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPOS_SOLICITUD_ADMIN_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_OTP_POR_ID_FN(
        P_ID_TIPO_OTP IN FIDE_TIPO_OTP_TB.ID_TIPO_OTP%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CATEGORIA_POR_ID_FN(
        P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MARCA_POR_ID_FN(
        P_ID_MARCA IN FIDE_MARCA_TB.ID_MARCA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_MOVIMIENTO_POR_ID_FN(
        P_ID_TIPO_MOVIMIENTO IN FIDE_TIPO_MOVIMIENTO_TB.ID_TIPO_MOVIMIENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CAMPANIA_POR_ID_FN(
        P_ID_CAMPANIA IN FIDE_CAMPANIA_TB.ID_CAMPANIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MONEDA_POR_ID_FN(
        P_ID_MONEDA IN FIDE_MONEDA_TB.ID_MONEDA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RAZA_POR_ID_FN(
        P_ID_RAZA IN FIDE_RAZA_TB.ID_RAZA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEXO_POR_ID_FN(
        P_ID_SEXO IN FIDE_SEXO_TB.ID_SEXO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_SOLICITUD_POR_ID_FN(
        P_ID_TIPO_SOLICITUD IN FIDE_TIPO_SOLICITUD_TB.ID_TIPO_SOLICITUD%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_RESPUESTA_POR_ID_FN(
        P_ID_TIPO_RESPUESTA IN FIDE_TIPO_RESPUESTA_TB.ID_TIPO_RESPUESTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_SEGUIMIENTO_POR_ID_FN(
        P_ID_TIPO_SEGUIMIENTO IN FIDE_TIPO_SEGUIMIENTO_TB.ID_TIPO_SEGUIMIENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TIPO_EVENTO_POR_ID_FN(
        P_ID_TIPO_EVENTO IN FIDE_TIPO_EVENTO_TB.ID_TIPO_EVENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PROVINCIAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PROVINCIA_POR_ID_FN(
        P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CANTONES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CANTON_POR_ID_FN(
        P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DISTRITOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DISTRITO_POR_ID_FN(
        P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       FUNCIONES COMPLEMENTARIAS PARA CRUD ADMIN
       DIRECCIONES, USUARIOS Y AUTENTICACION
       ============================================================ */

    FUNCTION FIDE_OBTENER_DIRECCIONES_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PREGUNTA_POR_ID_FN(
        P_ID_PREGUNTA IN FIDE_PREGUNTA_TB.ID_PREGUNTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CORREOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CORREO_POR_PK_FN(
        P_IDENTIFICACION IN FIDE_CORREO_TB.IDENTIFICACION%TYPE,
        P_CORREO         IN FIDE_CORREO_TB.CORREO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TELEFONOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TELEFONO_POR_PK_FN(
        P_IDENTIFICACION IN FIDE_TELEFONO_TB.IDENTIFICACION%TYPE,
        P_TELEFONO       IN FIDE_TELEFONO_TB.TELEFONO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CUENTAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_OTPS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_OTP_POR_ID_FN(
        P_ID_CODIGO_OTP IN FIDE_CODIGO_OTP_TB.ID_CODIGO_OTP%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_REFRESH_TOKENS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_REFRESH_TOKEN_POR_ID_FN(
        P_ID_REFRESH_TOKEN IN FIDE_REFRESH_TOKEN_TB.ID_REFRESH_TOKEN%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* ============================================================
       FUNCIONES COMPLEMENTARIAS PARA CRUD ADMIN
       TRANSACCIONALES, PIVOTES Y DETALLES
       ============================================================ */

    FUNCTION FIDE_OBTENER_VENTA_POR_ID_FN(
        P_ID_VENTA IN FIDE_VENTA_TB.ID_VENTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DONACION_POR_ID_FN(
        P_ID_DONACION IN FIDE_DONACION_TB.ID_DONACION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PERRITOS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_IMAGEN_PERRO_POR_ID_FN(
        P_ID_IMAGEN IN FIDE_PERRITO_IMAGE_TB.ID_IMAGEN%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_EVENTOS_PERRITO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_EVENTO_PERRITO_POR_ID_FN(
        P_ID_EVENTO IN FIDE_EVENTO_PERRITO_TB.ID_EVENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_TODOS_DETALLES_EVENTO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DETALLE_EVENTO_POR_ID_FN(
        P_ID_DETALLE_EVENTO IN FIDE_DETALLE_EVENTO_TB.ID_DETALLE_EVENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RESPUESTAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_RESPUESTA_POR_ID_FN(
        P_ID_RESPUESTA IN FIDE_RESPUESTA_TB.ID_RESPUESTA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CASA_CUNA_POR_ID_FN(
        P_ID_CASA_CUNA IN FIDE_CASA_CUNA_TB.ID_CASA_CUNA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_ADOPCION_POR_ID_FN(
        P_ID_ADOPCION IN FIDE_ADOPCION_TB.ID_ADOPCION%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_SEGUIMIENTO_POR_ID_FN(
        P_ID_SEGUIMIENTO IN FIDE_SEGUIMIENTO_TB.ID_SEGUIMIENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_EVIDENCIAS_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_EVIDENCIA_POR_ID_FN(
        P_ID_EVIDENCIA IN FIDE_EVIDENCIA_TB.ID_EVIDENCIA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CASAS_PERRITO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_CASA_PERRITO_POR_PK_FN(
        P_ID_CASA_CUNA IN FIDE_CASA_PERRITO_TB.ID_CASA_CUNA%TYPE,
        P_ID_PERRITO   IN FIDE_CASA_PERRITO_TB.ID_PERRITO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_VENTAS_FACTURA_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_VENTA_FACTURA_POR_PK_FN(
        P_ID_VENTA   IN FIDE_VENTA_FACTURA_TB.ID_VENTA%TYPE,
        P_ID_FACTURA IN FIDE_VENTA_FACTURA_TB.ID_FACTURA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DONACIONES_FACTURA_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_DONACION_FACTURA_POR_PK_FN(
        P_ID_DONACION IN FIDE_DONACION_FACTURA_TB.ID_DONACION%TYPE,
        P_ID_FACTURA  IN FIDE_DONACION_FACTURA_TB.ID_FACTURA%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAGOS_PAYPAL_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_PAGO_PAYPAL_POR_ID_FN(
        P_ID_PAGO IN FIDE_PAGO_PAYPAL_TB.ID_PAGO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_INVENTARIO_POR_ID_FN(
        P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_MOVIMIENTO_INVENTARIO_POR_ID_FN(
        P_ID_MOVIMIENTO IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_MOVIMIENTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_VENTAS_PRODUCTO_FN
    RETURN SYS_REFCURSOR;

    FUNCTION FIDE_OBTENER_VENTA_PRODUCTO_POR_PK_FN(
        P_ID_VENTA    IN FIDE_VENTA_PRODUCTO_TB.ID_VENTA%TYPE,
        P_ID_PRODUCTO IN FIDE_VENTA_PRODUCTO_TB.ID_PRODUCTO%TYPE
    )
    RETURN SYS_REFCURSOR;

    /* PROCEDURE FIDE_ESTADO_TB INSERT */

    PROCEDURE FIDE_ESTADO_INSERT_SP(
        P_NOMBRE_ESTADO IN FIDE_ESTADO_TB.NOMBRE_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_ESTADO_TB UPDATE */

    PROCEDURE FIDE_ESTADO_UPDATE_SP(
        P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO%TYPE,
        P_NOMBRE_ESTADO IN FIDE_ESTADO_TB.NOMBRE_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_ESTADO_TB DELETE */

    PROCEDURE FIDE_ESTADO_DELETE_SP(
        P_ID_ESTADO IN FIDE_ESTADO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_USUARIO_TB INSERT */

    PROCEDURE FIDE_TIPO_USUARIO_INSERT_SP(
        P_NOMBRE   IN FIDE_TIPO_USUARIO_TB.NOMBRE%TYPE,
        P_ID_ESTADO       IN FIDE_TIPO_USUARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_USUARIO_TB UPDATE */

    PROCEDURE FIDE_TIPO_USUARIO_UPDATE_SP(
        P_ID_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.ID_TIPO_USUARIO%TYPE,
        P_NOMBRE          IN FIDE_TIPO_USUARIO_TB.NOMBRE%TYPE,
        P_ID_ESTADO       IN FIDE_TIPO_USUARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_USUARIO_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_USUARIO_DELETE_SP(
        P_ID_TIPO_USUARIO IN FIDE_TIPO_USUARIO_TB.ID_TIPO_USUARIO%TYPE
    );

    /* PROCEDURE FIDE_USUARIO_TB INSERT */

    PROCEDURE FIDE_USUARIO_INSERT_SP(
        P_IDENTIFICACION     IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE,
        P_NOMBRE             IN FIDE_USUARIO_TB.NOMBRE%TYPE,
        P_APELLIDO_PATERNO   IN FIDE_USUARIO_TB.APELLIDO_PATERNO%TYPE,
        P_APELLIDO_MATERNO   IN FIDE_USUARIO_TB.APELLIDO_MATERNO%TYPE,
        P_ID_DIRECCION       IN FIDE_USUARIO_TB.ID_DIRECCION%TYPE,
        P_ID_TIPO_USUARIO    IN FIDE_USUARIO_TB.ID_TIPO_USUARIO%TYPE,
        P_ID_ESTADO          IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_USUARIO_TB UPDATE */

    PROCEDURE FIDE_USUARIO_UPDATE_SP(
        P_IDENTIFICACION     IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE,
        P_NOMBRE             IN FIDE_USUARIO_TB.NOMBRE%TYPE,
        P_APELLIDO_PATERNO   IN FIDE_USUARIO_TB.APELLIDO_PATERNO%TYPE,
        P_APELLIDO_MATERNO   IN FIDE_USUARIO_TB.APELLIDO_MATERNO%TYPE,
        P_ID_DIRECCION       IN FIDE_USUARIO_TB.ID_DIRECCION%TYPE,
        P_ID_TIPO_USUARIO    IN FIDE_USUARIO_TB.ID_TIPO_USUARIO%TYPE,
        P_ID_ESTADO          IN FIDE_USUARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_USUARIO_TB DELETE LOGICO */

    PROCEDURE FIDE_USUARIO_DELETE_SP(
        P_IDENTIFICACION IN FIDE_USUARIO_TB.IDENTIFICACION%TYPE
    );

    /* PROCEDURE FIDE_CORREO_TB INSERT */

    PROCEDURE FIDE_CORREO_INSERT_SP(
        P_IDENTIFICACION IN FIDE_CORREO_TB.IDENTIFICACION%TYPE,
        P_CORREO         IN FIDE_CORREO_TB.CORREO%TYPE,
        P_ID_ESTADO      IN FIDE_CORREO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CORREO_TB UPDATE */

    PROCEDURE FIDE_CORREO_UPDATE_SP(
        P_IDENTIFICACION IN FIDE_CORREO_TB.IDENTIFICACION%TYPE,
        P_CORREO         IN FIDE_CORREO_TB.CORREO%TYPE,
        P_ID_ESTADO      IN FIDE_CORREO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CORREO_TB DELETE LOGICO */

    PROCEDURE FIDE_CORREO_DELETE_SP(
        P_IDENTIFICACION IN FIDE_CORREO_TB.IDENTIFICACION%TYPE,
        P_CORREO         IN FIDE_CORREO_TB.CORREO%TYPE
    );

    /* PROCEDURE FIDE_TELEFONO_TB INSERT */

    PROCEDURE FIDE_TELEFONO_INSERT_SP(
        P_IDENTIFICACION IN FIDE_TELEFONO_TB.IDENTIFICACION%TYPE,
        P_TELEFONO       IN FIDE_TELEFONO_TB.TELEFONO%TYPE,
        P_ID_ESTADO      IN FIDE_TELEFONO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TELEFONO_TB UPDATE */

    PROCEDURE FIDE_TELEFONO_UPDATE_SP(
        P_IDENTIFICACION IN FIDE_TELEFONO_TB.IDENTIFICACION%TYPE,
        P_TELEFONO       IN FIDE_TELEFONO_TB.TELEFONO%TYPE,
        P_ID_ESTADO      IN FIDE_TELEFONO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TELEFONO_TB DELETE LOGICO */

    PROCEDURE FIDE_TELEFONO_DELETE_SP(
        P_IDENTIFICACION IN FIDE_TELEFONO_TB.IDENTIFICACION%TYPE,
        P_TELEFONO       IN FIDE_TELEFONO_TB.TELEFONO%TYPE
    );

    /* PROCEDURE FIDE_CUENTA_TB INSERT */

    PROCEDURE FIDE_CUENTA_INSERT_SP(
        P_IDENTIFICACION   IN FIDE_CUENTA_TB.IDENTIFICACION%TYPE,
        P_USUARIO          IN FIDE_CUENTA_TB.USUARIO%TYPE,
        P_PASSWORD_HASH    IN FIDE_CUENTA_TB.PASSWORD_HASH%TYPE,
        P_ID_ESTADO        IN FIDE_CUENTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CUENTA_TB UPDATE */

    PROCEDURE FIDE_CUENTA_UPDATE_SP(
        P_ID_CUENTA        IN FIDE_CUENTA_TB.ID_CUENTA%TYPE,
        P_IDENTIFICACION   IN FIDE_CUENTA_TB.IDENTIFICACION%TYPE,
        P_USUARIO          IN FIDE_CUENTA_TB.USUARIO%TYPE,
        P_PASSWORD_HASH    IN FIDE_CUENTA_TB.PASSWORD_HASH%TYPE,
        P_ID_ESTADO        IN FIDE_CUENTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CUENTA_TB DELETE LOGICO */

    PROCEDURE FIDE_CUENTA_DELETE_SP(
        P_ID_CUENTA IN FIDE_CUENTA_TB.ID_CUENTA%TYPE
    );

    /* PROCEDURE FIDE_TIPO_OTP_TB INSERT */

    PROCEDURE FIDE_TIPO_OTP_INSERT_SP(
        P_NOMBRE      IN FIDE_TIPO_OTP_TB.NOMBRE%TYPE,
        P_ID_ESTADO   IN FIDE_TIPO_OTP_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_OTP_TB UPDATE */

    PROCEDURE FIDE_TIPO_OTP_UPDATE_SP(
        P_ID_TIPO_OTP IN FIDE_TIPO_OTP_TB.ID_TIPO_OTP%TYPE,
        P_NOMBRE      IN FIDE_TIPO_OTP_TB.NOMBRE%TYPE,
        P_ID_ESTADO   IN FIDE_TIPO_OTP_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_OTP_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_OTP_DELETE_SP(
        P_ID_TIPO_OTP IN FIDE_TIPO_OTP_TB.ID_TIPO_OTP%TYPE
    );

    /* PROCEDURE FIDE_CODIGO_OTP_TB INSERT */

    PROCEDURE FIDE_CODIGO_OTP_INSERT_SP(
        P_ID_CUENTA         IN FIDE_CODIGO_OTP_TB.ID_CUENTA%TYPE,
        P_ID_TIPO_OTP       IN FIDE_CODIGO_OTP_TB.ID_TIPO_OTP%TYPE,
        P_CODIGO_HASH       IN FIDE_CODIGO_OTP_TB.CODIGO_HASH%TYPE,
        P_FECHA_EXPIRACION  IN FIDE_CODIGO_OTP_TB.FECHA_EXPIRACION%TYPE,
        P_FECHA_USO         IN FIDE_CODIGO_OTP_TB.FECHA_USO%TYPE,
        P_INTENTOS          IN FIDE_CODIGO_OTP_TB.INTENTOS%TYPE,
        P_FECHA_CREACION    IN FIDE_CODIGO_OTP_TB.FECHA_CREACION%TYPE,
        P_ID_ESTADO         IN FIDE_CODIGO_OTP_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CODIGO_OTP_TB UPDATE */

    PROCEDURE FIDE_CODIGO_OTP_UPDATE_SP(
        P_ID_CODIGO_OTP     IN FIDE_CODIGO_OTP_TB.ID_CODIGO_OTP%TYPE,
        P_ID_CUENTA         IN FIDE_CODIGO_OTP_TB.ID_CUENTA%TYPE,
        P_ID_TIPO_OTP       IN FIDE_CODIGO_OTP_TB.ID_TIPO_OTP%TYPE,
        P_CODIGO_HASH       IN FIDE_CODIGO_OTP_TB.CODIGO_HASH%TYPE,
        P_FECHA_EXPIRACION  IN FIDE_CODIGO_OTP_TB.FECHA_EXPIRACION%TYPE,
        P_FECHA_USO         IN FIDE_CODIGO_OTP_TB.FECHA_USO%TYPE,
        P_INTENTOS          IN FIDE_CODIGO_OTP_TB.INTENTOS%TYPE,
        P_FECHA_CREACION    IN FIDE_CODIGO_OTP_TB.FECHA_CREACION%TYPE,
        P_ID_ESTADO         IN FIDE_CODIGO_OTP_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CODIGO_OTP_TB DELETE LOGICO */

    PROCEDURE FIDE_CODIGO_OTP_DELETE_SP(
        P_ID_CODIGO_OTP IN FIDE_CODIGO_OTP_TB.ID_CODIGO_OTP%TYPE
    );

    /* PROCEDURE FIDE_REFRESH_TOKEN_TB INSERT */

    PROCEDURE FIDE_REFRESH_TOKEN_INSERT_SP(
        P_ID_CUENTA          IN FIDE_REFRESH_TOKEN_TB.ID_CUENTA%TYPE,
        P_TOKEN_HASH         IN FIDE_REFRESH_TOKEN_TB.TOKEN_HASH%TYPE,
        P_JTI                IN FIDE_REFRESH_TOKEN_TB.JTI%TYPE,
        P_IP_ADDRESS         IN FIDE_REFRESH_TOKEN_TB.IP_ADDRESS%TYPE,
        P_USER_AGENT         IN FIDE_REFRESH_TOKEN_TB.USER_AGENT%TYPE,
        P_FECHA_EXPIRACION   IN FIDE_REFRESH_TOKEN_TB.FECHA_EXPIRACION%TYPE,
        P_FECHA_REVOCACION   IN FIDE_REFRESH_TOKEN_TB.FECHA_REVOCACION%TYPE,
        P_ID_ESTADO          IN FIDE_REFRESH_TOKEN_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_REFRESH_TOKEN_TB UPDATE */

    PROCEDURE FIDE_REFRESH_TOKEN_UPDATE_SP(
        P_ID_REFRESH_TOKEN   IN FIDE_REFRESH_TOKEN_TB.ID_REFRESH_TOKEN%TYPE,
        P_ID_CUENTA          IN FIDE_REFRESH_TOKEN_TB.ID_CUENTA%TYPE,
        P_TOKEN_HASH         IN FIDE_REFRESH_TOKEN_TB.TOKEN_HASH%TYPE,
        P_JTI                IN FIDE_REFRESH_TOKEN_TB.JTI%TYPE,
        P_IP_ADDRESS         IN FIDE_REFRESH_TOKEN_TB.IP_ADDRESS%TYPE,
        P_USER_AGENT         IN FIDE_REFRESH_TOKEN_TB.USER_AGENT%TYPE,
        P_FECHA_EXPIRACION   IN FIDE_REFRESH_TOKEN_TB.FECHA_EXPIRACION%TYPE,
        P_FECHA_REVOCACION   IN FIDE_REFRESH_TOKEN_TB.FECHA_REVOCACION%TYPE,
        P_ID_ESTADO          IN FIDE_REFRESH_TOKEN_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_REFRESH_TOKEN_TB DELETE LOGICO */

    PROCEDURE FIDE_REFRESH_TOKEN_DELETE_SP(
        P_ID_REFRESH_TOKEN IN FIDE_REFRESH_TOKEN_TB.ID_REFRESH_TOKEN%TYPE
    );

    /* PROCEDURE FIDE_PAIS_TB INSERT */

    PROCEDURE FIDE_PAIS_INSERT_SP(
        P_NOMBRE     IN FIDE_PAIS_TB.NOMBRE%TYPE,
        P_ID_ESTADO  IN FIDE_PAIS_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PAIS_TB UPDATE */

    PROCEDURE FIDE_PAIS_UPDATE_SP(
        P_ID_PAIS    IN FIDE_PAIS_TB.ID_PAIS%TYPE,
        P_NOMBRE     IN FIDE_PAIS_TB.NOMBRE%TYPE,
        P_ID_ESTADO  IN FIDE_PAIS_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PAIS_TB DELETE LOGICO */

    PROCEDURE FIDE_PAIS_DELETE_SP(
        P_ID_PAIS IN FIDE_PAIS_TB.ID_PAIS%TYPE
    );

    /* PROCEDURE FIDE_PROVINCIA_TB INSERT */

    PROCEDURE FIDE_PROVINCIA_INSERT_SP(
        P_NOMBRE       IN FIDE_PROVINCIA_TB.NOMBRE%TYPE,
        P_ID_PAIS      IN FIDE_PROVINCIA_TB.ID_PAIS%TYPE,
        P_ID_ESTADO    IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PROVINCIA_TB UPDATE */

    PROCEDURE FIDE_PROVINCIA_UPDATE_SP(
        P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE,
        P_NOMBRE       IN FIDE_PROVINCIA_TB.NOMBRE%TYPE,
        P_ID_PAIS      IN FIDE_PROVINCIA_TB.ID_PAIS%TYPE,
        P_ID_ESTADO    IN FIDE_PROVINCIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PROVINCIA_TB DELETE LOGICO */

    PROCEDURE FIDE_PROVINCIA_DELETE_SP(
        P_ID_PROVINCIA IN FIDE_PROVINCIA_TB.ID_PROVINCIA%TYPE
    );

    /* PROCEDURE FIDE_CANTON_TB INSERT */

    PROCEDURE FIDE_CANTON_INSERT_SP(
        P_NOMBRE        IN FIDE_CANTON_TB.NOMBRE%TYPE,
        P_ID_PROVINCIA  IN FIDE_CANTON_TB.ID_PROVINCIA%TYPE,
        P_ID_ESTADO     IN FIDE_CANTON_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CANTON_TB UPDATE */

    PROCEDURE FIDE_CANTON_UPDATE_SP(
        P_ID_CANTON     IN FIDE_CANTON_TB.ID_CANTON%TYPE,
        P_NOMBRE        IN FIDE_CANTON_TB.NOMBRE%TYPE,
        P_ID_PROVINCIA  IN FIDE_CANTON_TB.ID_PROVINCIA%TYPE,
        P_ID_ESTADO     IN FIDE_CANTON_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CANTON_TB DELETE LOGICO */

    PROCEDURE FIDE_CANTON_DELETE_SP(
        P_ID_CANTON IN FIDE_CANTON_TB.ID_CANTON%TYPE
    );

    /* PROCEDURE FIDE_DISTRITO_TB INSERT */

    PROCEDURE FIDE_DISTRITO_INSERT_SP(
        P_NOMBRE       IN FIDE_DISTRITO_TB.NOMBRE%TYPE,
        P_ID_CANTON    IN FIDE_DISTRITO_TB.ID_CANTON%TYPE,
        P_ID_ESTADO    IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DISTRITO_TB UPDATE */

    PROCEDURE FIDE_DISTRITO_UPDATE_SP(
        P_ID_DISTRITO  IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE,
        P_NOMBRE       IN FIDE_DISTRITO_TB.NOMBRE%TYPE,
        P_ID_CANTON    IN FIDE_DISTRITO_TB.ID_CANTON%TYPE,
        P_ID_ESTADO    IN FIDE_DISTRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DISTRITO_TB DELETE LOGICO */

    PROCEDURE FIDE_DISTRITO_DELETE_SP(
        P_ID_DISTRITO IN FIDE_DISTRITO_TB.ID_DISTRITO%TYPE
    );

    /* PROCEDURE FIDE_DIRECCION_TB INSERT */

    PROCEDURE FIDE_DIRECCION_INSERT_SP(
        P_ID_DISTRITO  IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
        P_CALLE        IN FIDE_DIRECCION_TB.CALLE%TYPE,
        P_NUMERO       IN FIDE_DIRECCION_TB.NUMERO%TYPE,
        P_ID_ESTADO    IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DIRECCION_TB UPDATE */

    PROCEDURE FIDE_DIRECCION_UPDATE_SP(
        P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE,
        P_ID_DISTRITO  IN FIDE_DIRECCION_TB.ID_DISTRITO%TYPE,
        P_CALLE        IN FIDE_DIRECCION_TB.CALLE%TYPE,
        P_NUMERO       IN FIDE_DIRECCION_TB.NUMERO%TYPE,
        P_ID_ESTADO    IN FIDE_DIRECCION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DIRECCION_TB DELETE LOGICO */

    PROCEDURE FIDE_DIRECCION_DELETE_SP(
        P_ID_DIRECCION IN FIDE_DIRECCION_TB.ID_DIRECCION%TYPE
    );

    /* PROCEDURE FIDE_CATEGORIA_TB INSERT */

    PROCEDURE FIDE_CATEGORIA_INSERT_SP(
        P_NOMBRE       IN FIDE_CATEGORIA_TB.NOMBRE%TYPE,
        P_ID_ESTADO    IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CATEGORIA_TB UPDATE */

    PROCEDURE FIDE_CATEGORIA_UPDATE_SP(
        P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE,
        P_NOMBRE       IN FIDE_CATEGORIA_TB.NOMBRE%TYPE,
        P_ID_ESTADO    IN FIDE_CATEGORIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CATEGORIA_TB DELETE LOGICO */

    PROCEDURE FIDE_CATEGORIA_DELETE_SP(
        P_ID_CATEGORIA IN FIDE_CATEGORIA_TB.ID_CATEGORIA%TYPE
    );

    /* PROCEDURE FIDE_MARCA_TB INSERT */

    PROCEDURE FIDE_MARCA_INSERT_SP(
        P_NOMBRE       IN FIDE_MARCA_TB.NOMBRE%TYPE,
        P_ID_ESTADO    IN FIDE_MARCA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MARCA_TB UPDATE */

    PROCEDURE FIDE_MARCA_UPDATE_SP(
        P_ID_MARCA     IN FIDE_MARCA_TB.ID_MARCA%TYPE,
        P_NOMBRE       IN FIDE_MARCA_TB.NOMBRE%TYPE,
        P_ID_ESTADO    IN FIDE_MARCA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MARCA_TB DELETE LOGICO */

    PROCEDURE FIDE_MARCA_DELETE_SP(
        P_ID_MARCA IN FIDE_MARCA_TB.ID_MARCA%TYPE
    );

    /* PROCEDURE FIDE_PRODUCTO_TB INSERT */

    PROCEDURE FIDE_PRODUCTO_INSERT_SP(
        P_NOMBRE       IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
        P_DESCRIPCION  IN FIDE_PRODUCTO_TB.DESCRIPCION%TYPE,
        P_PRECIO       IN FIDE_PRODUCTO_TB.PRECIO%TYPE,
        P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
        P_ID_ESTADO    IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PRODUCTO_TB UPDATE */

    PROCEDURE FIDE_PRODUCTO_UPDATE_SP(
        P_ID_PRODUCTO  IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE,
        P_NOMBRE       IN FIDE_PRODUCTO_TB.NOMBRE%TYPE,
        P_DESCRIPCION  IN FIDE_PRODUCTO_TB.DESCRIPCION%TYPE,
        P_PRECIO       IN FIDE_PRODUCTO_TB.PRECIO%TYPE,
        P_ID_CATEGORIA IN FIDE_PRODUCTO_TB.ID_CATEGORIA%TYPE,
        P_ID_ESTADO    IN FIDE_PRODUCTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PRODUCTO_TB DELETE LOGICO */

    PROCEDURE FIDE_PRODUCTO_DELETE_SP(
        P_ID_PRODUCTO IN FIDE_PRODUCTO_TB.ID_PRODUCTO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_TB INSERT */

    PROCEDURE FIDE_VENTA_INSERT_SP(
        P_IDENTIFICACION  IN FIDE_VENTA_TB.IDENTIFICACION%TYPE,
        P_TOTAL_VENTA     IN FIDE_VENTA_TB.TOTAL_VENTA%TYPE,
        P_FECHA_VENTA     IN FIDE_VENTA_TB.FECHA_VENTA%TYPE,
        P_ID_ESTADO       IN FIDE_VENTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_TB UPDATE */

    PROCEDURE FIDE_VENTA_UPDATE_SP(
        P_ID_VENTA        IN FIDE_VENTA_TB.ID_VENTA%TYPE,
        P_IDENTIFICACION  IN FIDE_VENTA_TB.IDENTIFICACION%TYPE,
        P_TOTAL_VENTA     IN FIDE_VENTA_TB.TOTAL_VENTA%TYPE,
        P_FECHA_VENTA     IN FIDE_VENTA_TB.FECHA_VENTA%TYPE,
        P_ID_ESTADO       IN FIDE_VENTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_TB DELETE LOGICO */

    PROCEDURE FIDE_VENTA_DELETE_SP(
        P_ID_VENTA IN FIDE_VENTA_TB.ID_VENTA%TYPE
    );

    /* PROCEDURE FIDE_VENTA_PRODUCTO_TB INSERT */

    PROCEDURE FIDE_VENTA_PRODUCTO_INSERT_SP(
        P_ID_VENTA           IN FIDE_VENTA_PRODUCTO_TB.ID_VENTA%TYPE,
        P_ID_PRODUCTO        IN FIDE_VENTA_PRODUCTO_TB.ID_PRODUCTO%TYPE,
        P_ID_TIPO_MOVIMIENTO IN FIDE_VENTA_PRODUCTO_TB.ID_TIPO_MOVIMIENTO%TYPE,
        P_CANTIDAD           IN FIDE_VENTA_PRODUCTO_TB.CANTIDAD%TYPE,
        P_TOTAL              IN FIDE_VENTA_PRODUCTO_TB.TOTAL%TYPE,
        P_ID_ESTADO          IN FIDE_VENTA_PRODUCTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_PRODUCTO_TB UPDATE */

    PROCEDURE FIDE_VENTA_PRODUCTO_UPDATE_SP(
        P_ID_VENTA           IN FIDE_VENTA_PRODUCTO_TB.ID_VENTA%TYPE,
        P_ID_PRODUCTO        IN FIDE_VENTA_PRODUCTO_TB.ID_PRODUCTO%TYPE,
        P_ID_TIPO_MOVIMIENTO IN FIDE_VENTA_PRODUCTO_TB.ID_TIPO_MOVIMIENTO%TYPE,
        P_CANTIDAD           IN FIDE_VENTA_PRODUCTO_TB.CANTIDAD%TYPE,
        P_TOTAL              IN FIDE_VENTA_PRODUCTO_TB.TOTAL%TYPE,
        P_ID_ESTADO          IN FIDE_VENTA_PRODUCTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_PRODUCTO_TB DELETE LOGICO */

    PROCEDURE FIDE_VENTA_PRODUCTO_DELETE_SP(
        P_ID_VENTA    IN FIDE_VENTA_PRODUCTO_TB.ID_VENTA%TYPE,
        P_ID_PRODUCTO IN FIDE_VENTA_PRODUCTO_TB.ID_PRODUCTO%TYPE
    );

    /* PROCEDURE FIDE_INVENTARIO_TB INSERT */

    PROCEDURE FIDE_INVENTARIO_INSERT_SP(
        P_ID_PRODUCTO   IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
        P_CANTIDAD      IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
        P_ID_ESTADO     IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_INVENTARIO_TB UPDATE */

    PROCEDURE FIDE_INVENTARIO_UPDATE_SP(
        P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE,
        P_ID_PRODUCTO   IN FIDE_INVENTARIO_TB.ID_PRODUCTO%TYPE,
        P_CANTIDAD      IN FIDE_INVENTARIO_TB.CANTIDAD%TYPE,
        P_ID_ESTADO     IN FIDE_INVENTARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_INVENTARIO_TB DELETE LOGICO */

    PROCEDURE FIDE_INVENTARIO_DELETE_SP(
        P_ID_INVENTARIO IN FIDE_INVENTARIO_TB.ID_INVENTARIO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_MOVIMIENTO_TB INSERT */

    PROCEDURE FIDE_TIPO_MOVIMIENTO_INSERT_SP(
        P_NOMBRE             IN FIDE_TIPO_MOVIMIENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO          IN FIDE_TIPO_MOVIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_MOVIMIENTO_TB UPDATE */

    PROCEDURE FIDE_TIPO_MOVIMIENTO_UPDATE_SP(
        P_ID_TIPO_MOVIMIENTO IN FIDE_TIPO_MOVIMIENTO_TB.ID_TIPO_MOVIMIENTO%TYPE,
        P_NOMBRE             IN FIDE_TIPO_MOVIMIENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO          IN FIDE_TIPO_MOVIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_MOVIMIENTO_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_MOVIMIENTO_DELETE_SP(
        P_ID_TIPO_MOVIMIENTO IN FIDE_TIPO_MOVIMIENTO_TB.ID_TIPO_MOVIMIENTO%TYPE
    );

    /* PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_TB INSERT */

    PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_INSERT_SP(
        P_ID_PRODUCTO         IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_PRODUCTO%TYPE,
        P_ID_TIPO_MOVIMIENTO  IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO%TYPE,
        P_CANTIDAD            IN FIDE_MOVIMIENTO_INVENTARIO_TB.CANTIDAD%TYPE,
        P_FECHA_MOVIMIENTO    IN FIDE_MOVIMIENTO_INVENTARIO_TB.FECHA_MOVIMIENTO%TYPE,
        P_ID_ESTADO           IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_TB UPDATE */

    PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_UPDATE_SP(
        P_ID_MOVIMIENTO       IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_MOVIMIENTO%TYPE,
        P_ID_PRODUCTO         IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_PRODUCTO%TYPE,
        P_ID_TIPO_MOVIMIENTO  IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO%TYPE,
        P_CANTIDAD            IN FIDE_MOVIMIENTO_INVENTARIO_TB.CANTIDAD%TYPE,
        P_FECHA_MOVIMIENTO    IN FIDE_MOVIMIENTO_INVENTARIO_TB.FECHA_MOVIMIENTO%TYPE,
        P_ID_ESTADO           IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_TB DELETE LOGICO */

    PROCEDURE FIDE_MOVIMIENTO_INVENTARIO_DELETE_SP(
        P_ID_MOVIMIENTO IN FIDE_MOVIMIENTO_INVENTARIO_TB.ID_MOVIMIENTO%TYPE
    );

    /* PROCEDURE FIDE_MONEDA_TB INSERT */

    PROCEDURE FIDE_MONEDA_INSERT_SP(
        P_NOMBRE     IN FIDE_MONEDA_TB.NOMBRE%TYPE,
        P_SIMBOLO    IN FIDE_MONEDA_TB.SIMBOLO%TYPE,
        P_ID_ESTADO  IN FIDE_MONEDA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MONEDA_TB UPDATE */

    PROCEDURE FIDE_MONEDA_UPDATE_SP(
        P_ID_MONEDA  IN FIDE_MONEDA_TB.ID_MONEDA%TYPE,
        P_NOMBRE     IN FIDE_MONEDA_TB.NOMBRE%TYPE,
        P_SIMBOLO    IN FIDE_MONEDA_TB.SIMBOLO%TYPE,
        P_ID_ESTADO  IN FIDE_MONEDA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_MONEDA_TB DELETE LOGICO */

    PROCEDURE FIDE_MONEDA_DELETE_SP(
        P_ID_MONEDA IN FIDE_MONEDA_TB.ID_MONEDA%TYPE
    );

    /* PROCEDURE FIDE_FACTURA_TB INSERT */

    PROCEDURE FIDE_FACTURA_INSERT_SP(
        P_ID_MONEDA   IN FIDE_FACTURA_TB.ID_MONEDA%TYPE,
        P_TOTAL       IN FIDE_FACTURA_TB.TOTAL%TYPE,
        P_FECHA       IN FIDE_FACTURA_TB.FECHA_FACTURA%TYPE,
        P_ID_ESTADO   IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_FACTURA_TB UPDATE */

    PROCEDURE FIDE_FACTURA_UPDATE_SP(
        P_ID_FACTURA  IN FIDE_FACTURA_TB.ID_FACTURA%TYPE,
        P_ID_MONEDA   IN FIDE_FACTURA_TB.ID_MONEDA%TYPE,
        P_TOTAL       IN FIDE_FACTURA_TB.TOTAL%TYPE,
        P_FECHA       IN FIDE_FACTURA_TB.FECHA_FACTURA%TYPE,
        P_ID_ESTADO   IN FIDE_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_FACTURA_TB DELETE LOGICO */

    PROCEDURE FIDE_FACTURA_DELETE_SP(
        P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE
    );

    /* PROCEDURE FIDE_VENTA_FACTURA_TB INSERT */

    PROCEDURE FIDE_VENTA_FACTURA_INSERT_SP(
        P_ID_VENTA   IN FIDE_VENTA_FACTURA_TB.ID_VENTA%TYPE,
        P_ID_FACTURA IN FIDE_VENTA_FACTURA_TB.ID_FACTURA%TYPE,
        P_ID_ESTADO  IN FIDE_VENTA_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_FACTURA_TB UPDATE */

    PROCEDURE FIDE_VENTA_FACTURA_UPDATE_SP(
        P_ID_VENTA   IN FIDE_VENTA_FACTURA_TB.ID_VENTA%TYPE,
        P_ID_FACTURA IN FIDE_VENTA_FACTURA_TB.ID_FACTURA%TYPE,
        P_ID_ESTADO  IN FIDE_VENTA_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_VENTA_FACTURA_TB DELETE LOGICO */

    PROCEDURE FIDE_VENTA_FACTURA_DELETE_SP(
        P_ID_VENTA   IN FIDE_VENTA_FACTURA_TB.ID_VENTA%TYPE,
        P_ID_FACTURA IN FIDE_VENTA_FACTURA_TB.ID_FACTURA%TYPE
    );

    /* PROCEDURE FIDE_DONACION_FACTURA_TB INSERT */

    PROCEDURE FIDE_DONACION_FACTURA_INSERT_SP(
        P_ID_DONACION IN FIDE_DONACION_FACTURA_TB.ID_DONACION%TYPE,
        P_ID_FACTURA  IN FIDE_DONACION_FACTURA_TB.ID_FACTURA%TYPE,
        P_ID_ESTADO   IN FIDE_DONACION_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DONACION_FACTURA_TB UPDATE */

    PROCEDURE FIDE_DONACION_FACTURA_UPDATE_SP(
        P_ID_DONACION IN FIDE_DONACION_FACTURA_TB.ID_DONACION%TYPE,
        P_ID_FACTURA  IN FIDE_DONACION_FACTURA_TB.ID_FACTURA%TYPE,
        P_ID_ESTADO   IN FIDE_DONACION_FACTURA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DONACION_FACTURA_TB DELETE LOGICO */

    PROCEDURE FIDE_DONACION_FACTURA_DELETE_SP(
        P_ID_DONACION IN FIDE_DONACION_FACTURA_TB.ID_DONACION%TYPE,
        P_ID_FACTURA  IN FIDE_DONACION_FACTURA_TB.ID_FACTURA%TYPE
    );

    /* PROCEDURE FIDE_PAGO_PAYPAL_TB INSERT */

    PROCEDURE FIDE_PAGO_PAYPAL_INSERT_SP(
        P_ID_FACTURA        IN FIDE_PAGO_PAYPAL_TB.ID_FACTURA%TYPE,
        P_PAYPAL_ORDER_ID   IN FIDE_PAGO_PAYPAL_TB.PAYPAL_ORDER_ID%TYPE,
        P_PAYPAL_CAPTURE_ID IN FIDE_PAGO_PAYPAL_TB.PAYPAL_CAPTURE_ID%TYPE,
        P_FECHA_PAGO        IN FIDE_PAGO_PAYPAL_TB.FECHA_PAGO%TYPE,
        P_ID_ESTADO         IN FIDE_PAGO_PAYPAL_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PAGO_PAYPAL_TB UPDATE */

    PROCEDURE FIDE_PAGO_PAYPAL_UPDATE_SP(
        P_ID_PAGO           IN FIDE_PAGO_PAYPAL_TB.ID_PAGO%TYPE,
        P_ID_FACTURA        IN FIDE_PAGO_PAYPAL_TB.ID_FACTURA%TYPE,
        P_PAYPAL_ORDER_ID   IN FIDE_PAGO_PAYPAL_TB.PAYPAL_ORDER_ID%TYPE,
        P_PAYPAL_CAPTURE_ID IN FIDE_PAGO_PAYPAL_TB.PAYPAL_CAPTURE_ID%TYPE,
        P_FECHA_PAGO        IN FIDE_PAGO_PAYPAL_TB.FECHA_PAGO%TYPE,
        P_ID_ESTADO         IN FIDE_PAGO_PAYPAL_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PAGO_PAYPAL_TB DELETE LOGICO */

    PROCEDURE FIDE_PAGO_PAYPAL_DELETE_SP(
        P_ID_PAGO IN FIDE_PAGO_PAYPAL_TB.ID_PAGO%TYPE
    );

    /* PROCEDURE FIDE_RAZA_TB INSERT */

    PROCEDURE FIDE_RAZA_INSERT_SP(
        P_NOMBRE    IN FIDE_RAZA_TB.NOMBRE%TYPE,
        P_ID_ESTADO IN FIDE_RAZA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_RAZA_TB UPDATE */

    PROCEDURE FIDE_RAZA_UPDATE_SP(
        P_ID_RAZA   IN FIDE_RAZA_TB.ID_RAZA%TYPE,
        P_NOMBRE    IN FIDE_RAZA_TB.NOMBRE%TYPE,
        P_ID_ESTADO IN FIDE_RAZA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_RAZA_TB DELETE LOGICO */

    PROCEDURE FIDE_RAZA_DELETE_SP(
        P_ID_RAZA IN FIDE_RAZA_TB.ID_RAZA%TYPE
    );

    /* PROCEDURE FIDE_SEXO_TB INSERT */

    PROCEDURE FIDE_SEXO_INSERT_SP(
        P_NOMBRE    IN FIDE_SEXO_TB.NOMBRE%TYPE,
        P_ID_ESTADO IN FIDE_SEXO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SEXO_TB UPDATE */

    PROCEDURE FIDE_SEXO_UPDATE_SP(
        P_ID_SEXO   IN FIDE_SEXO_TB.ID_SEXO%TYPE,
        P_NOMBRE    IN FIDE_SEXO_TB.NOMBRE%TYPE,
        P_ID_ESTADO IN FIDE_SEXO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SEXO_TB DELETE LOGICO */

    PROCEDURE FIDE_SEXO_DELETE_SP(
        P_ID_SEXO IN FIDE_SEXO_TB.ID_SEXO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_TB INSERT */

    PROCEDURE FIDE_PERRITO_INSERT_SP(
        P_NOMBRE       IN FIDE_PERRITO_TB.NOMBRE%TYPE,
        P_FECHA_INGRESO IN FIDE_PERRITO_TB.FECHA_INGRESO%TYPE,
        P_EDAD         IN FIDE_PERRITO_TB.EDAD%TYPE,
        P_PESO         IN FIDE_PERRITO_TB.PESO%TYPE,
        P_ESTATURA     IN FIDE_PERRITO_TB.ESTATURA%TYPE,
        P_ID_SEXO      IN FIDE_PERRITO_TB.ID_SEXO%TYPE,
        P_ID_RAZA      IN FIDE_PERRITO_TB.ID_RAZA%TYPE,
        P_ID_ESTADO    IN FIDE_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_TB UPDATE */

    PROCEDURE FIDE_PERRITO_UPDATE_SP(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE,
        P_NOMBRE     IN FIDE_PERRITO_TB.NOMBRE%TYPE,
        P_EDAD       IN FIDE_PERRITO_TB.EDAD%TYPE,
        P_PESO       IN FIDE_PERRITO_TB.PESO%TYPE,
        P_ESTATURA   IN FIDE_PERRITO_TB.ESTATURA%TYPE,
        P_ID_SEXO    IN FIDE_PERRITO_TB.ID_SEXO%TYPE,
        P_ID_RAZA    IN FIDE_PERRITO_TB.ID_RAZA%TYPE,
        P_ID_ESTADO  IN FIDE_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_TB DELETE LOGICO */

    PROCEDURE FIDE_PERRITO_DELETE_SP(
        P_ID_PERRITO IN FIDE_PERRITO_TB.ID_PERRITO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_IMAGE_TB INSERT */

    PROCEDURE FIDE_PERRITO_IMAGE_INSERT_SP(
        P_ID_PERRITO  IN FIDE_PERRITO_IMAGE_TB.ID_PERRITO%TYPE,
        P_IMAGE_URL   IN FIDE_PERRITO_IMAGE_TB.IMAGE_URL%TYPE,
        P_ID_ESTADO   IN FIDE_PERRITO_IMAGE_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_IMAGE_TB UPDATE */

    PROCEDURE FIDE_PERRITO_IMAGE_UPDATE_SP(
        P_ID_IMAGEN   IN FIDE_PERRITO_IMAGE_TB.ID_IMAGEN%TYPE,
        P_ID_PERRITO  IN FIDE_PERRITO_IMAGE_TB.ID_PERRITO%TYPE,
        P_IMAGE_URL   IN FIDE_PERRITO_IMAGE_TB.IMAGE_URL%TYPE,
        P_ID_ESTADO   IN FIDE_PERRITO_IMAGE_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PERRITO_IMAGE_TB DELETE LOGICO */

    PROCEDURE FIDE_PERRITO_IMAGE_DELETE_SP(
        P_ID_IMAGEN IN FIDE_PERRITO_IMAGE_TB.ID_IMAGEN%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SOLICITUD_TB INSERT */

    PROCEDURE FIDE_TIPO_SOLICITUD_INSERT_SP(
        P_NOMBRE            IN FIDE_TIPO_SOLICITUD_TB.NOMBRE%TYPE,
        P_ID_ESTADO         IN FIDE_TIPO_SOLICITUD_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SOLICITUD_TB UPDATE */

    PROCEDURE FIDE_TIPO_SOLICITUD_UPDATE_SP(
        P_ID_TIPO_SOLICITUD IN FIDE_TIPO_SOLICITUD_TB.ID_TIPO_SOLICITUD%TYPE,
        P_NOMBRE            IN FIDE_TIPO_SOLICITUD_TB.NOMBRE%TYPE,
        P_ID_ESTADO         IN FIDE_TIPO_SOLICITUD_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SOLICITUD_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_SOLICITUD_DELETE_SP(
        P_ID_TIPO_SOLICITUD IN FIDE_TIPO_SOLICITUD_TB.ID_TIPO_SOLICITUD%TYPE
    );

    /* PROCEDURE FIDE_SOLICITUD_TB INSERT */

    PROCEDURE FIDE_SOLICITUD_INSERT_SP(
        P_IDENTIFICACION    IN FIDE_SOLICITUD_TB.IDENTIFICACION%TYPE,
        P_ID_PERRITO        IN FIDE_SOLICITUD_TB.ID_PERRITO%TYPE,
        P_ID_TIPO_SOLICITUD IN FIDE_SOLICITUD_TB.ID_TIPO_SOLICITUD%TYPE,
        P_ID_ESTADO         IN FIDE_SOLICITUD_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SOLICITUD_TB UPDATE */

    PROCEDURE FIDE_SOLICITUD_UPDATE_SP(
        P_ID_SOLICITUD      IN FIDE_SOLICITUD_TB.ID_SOLICITUD%TYPE,
        P_IDENTIFICACION    IN FIDE_SOLICITUD_TB.IDENTIFICACION%TYPE,
        P_ID_PERRITO        IN FIDE_SOLICITUD_TB.ID_PERRITO%TYPE,
        P_ID_TIPO_SOLICITUD IN FIDE_SOLICITUD_TB.ID_TIPO_SOLICITUD%TYPE,
        P_ID_ESTADO         IN FIDE_SOLICITUD_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SOLICITUD_TB DELETE LOGICO */

    PROCEDURE FIDE_SOLICITUD_DELETE_SP(
        P_ID_SOLICITUD IN FIDE_SOLICITUD_TB.ID_SOLICITUD%TYPE
    );

    /* PROCEDURE FIDE_TIPO_RESPUESTA_TB INSERT */

    PROCEDURE FIDE_TIPO_RESPUESTA_INSERT_SP(
        P_NOMBRE            IN FIDE_TIPO_RESPUESTA_TB.NOMBRE%TYPE,
        P_ID_ESTADO         IN FIDE_TIPO_RESPUESTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_RESPUESTA_TB UPDATE */

    PROCEDURE FIDE_TIPO_RESPUESTA_UPDATE_SP(
        P_ID_TIPO_RESPUESTA IN FIDE_TIPO_RESPUESTA_TB.ID_TIPO_RESPUESTA%TYPE,
        P_NOMBRE            IN FIDE_TIPO_RESPUESTA_TB.NOMBRE%TYPE,
        P_ID_ESTADO         IN FIDE_TIPO_RESPUESTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_RESPUESTA_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_RESPUESTA_DELETE_SP(
        P_ID_TIPO_RESPUESTA IN FIDE_TIPO_RESPUESTA_TB.ID_TIPO_RESPUESTA%TYPE
    );

    /* PROCEDURE FIDE_PREGUNTA_TB INSERT */

    PROCEDURE FIDE_PREGUNTA_INSERT_SP(
        P_PREGUNTA          IN FIDE_PREGUNTA_TB.PREGUNTA%TYPE,
        P_ID_TIPO_RESPUESTA IN FIDE_PREGUNTA_TB.ID_TIPO_RESPUESTA%TYPE,
        P_ID_ESTADO         IN FIDE_PREGUNTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PREGUNTA_TB UPDATE */

    PROCEDURE FIDE_PREGUNTA_UPDATE_SP(
        P_ID_PREGUNTA       IN FIDE_PREGUNTA_TB.ID_PREGUNTA%TYPE,
        P_PREGUNTA          IN FIDE_PREGUNTA_TB.PREGUNTA%TYPE,
        P_ID_TIPO_RESPUESTA IN FIDE_PREGUNTA_TB.ID_TIPO_RESPUESTA%TYPE,
        P_ID_ESTADO         IN FIDE_PREGUNTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_PREGUNTA_TB DELETE LOGICO */

    PROCEDURE FIDE_PREGUNTA_DELETE_SP(
        P_ID_PREGUNTA IN FIDE_PREGUNTA_TB.ID_PREGUNTA%TYPE
    );

    /* PROCEDURE FIDE_RESPUESTA_TB INSERT */

    PROCEDURE FIDE_RESPUESTA_INSERT_SP(
        P_ID_SOLICITUD IN FIDE_RESPUESTA_TB.ID_SOLICITUD%TYPE,
        P_ID_PREGUNTA  IN FIDE_RESPUESTA_TB.ID_PREGUNTA%TYPE,
        P_RESPUESTA    IN FIDE_RESPUESTA_TB.RESPUESTA%TYPE,
        P_ID_ESTADO    IN FIDE_RESPUESTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_RESPUESTA_TB UPDATE */

    PROCEDURE FIDE_RESPUESTA_UPDATE_SP(
        P_ID_RESPUESTA IN FIDE_RESPUESTA_TB.ID_RESPUESTA%TYPE,
        P_ID_SOLICITUD IN FIDE_RESPUESTA_TB.ID_SOLICITUD%TYPE,
        P_ID_PREGUNTA  IN FIDE_RESPUESTA_TB.ID_PREGUNTA%TYPE,
        P_RESPUESTA    IN FIDE_RESPUESTA_TB.RESPUESTA%TYPE,
        P_ID_ESTADO    IN FIDE_RESPUESTA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_RESPUESTA_TB DELETE LOGICO */

    PROCEDURE FIDE_RESPUESTA_DELETE_SP(
        P_ID_RESPUESTA IN FIDE_RESPUESTA_TB.ID_RESPUESTA%TYPE
    );

    /* PROCEDURE FIDE_CASA_CUNA_TB INSERT */

    PROCEDURE FIDE_CASA_CUNA_INSERT_SP(
        P_NOMBRE         IN FIDE_CASA_CUNA_TB.NOMBRE%TYPE,
        P_ID_DIRECCION   IN FIDE_CASA_CUNA_TB.ID_DIRECCION%TYPE,
        P_IDENTIFICACION IN FIDE_CASA_CUNA_TB.IDENTIFICACION%TYPE,
        P_ID_SOLICITUD   IN FIDE_CASA_CUNA_TB.ID_SOLICITUD%TYPE,
        P_ID_ESTADO      IN FIDE_CASA_CUNA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CASA_CUNA_TB UPDATE */

    PROCEDURE FIDE_CASA_CUNA_UPDATE_SP(
        P_ID_CASA_CUNA   IN FIDE_CASA_CUNA_TB.ID_CASA_CUNA%TYPE,
        P_NOMBRE         IN FIDE_CASA_CUNA_TB.NOMBRE%TYPE,
        P_ID_DIRECCION   IN FIDE_CASA_CUNA_TB.ID_DIRECCION%TYPE,
        P_IDENTIFICACION IN FIDE_CASA_CUNA_TB.IDENTIFICACION%TYPE,
        P_ID_SOLICITUD   IN FIDE_CASA_CUNA_TB.ID_SOLICITUD%TYPE,
        P_ID_ESTADO      IN FIDE_CASA_CUNA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CASA_CUNA_TB DELETE LOGICO */

    PROCEDURE FIDE_CASA_CUNA_DELETE_SP(
        P_ID_CASA_CUNA IN FIDE_CASA_CUNA_TB.ID_CASA_CUNA%TYPE
    );

    /* PROCEDURE FIDE_CASA_PERRITO_TB INSERT */

    PROCEDURE FIDE_CASA_PERRITO_INSERT_SP(
        P_ID_CASA_CUNA IN FIDE_CASA_PERRITO_TB.ID_CASA_CUNA%TYPE,
        P_ID_PERRITO   IN FIDE_CASA_PERRITO_TB.ID_PERRITO%TYPE,
        P_ID_ESTADO    IN FIDE_CASA_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CASA_PERRITO_TB UPDATE */

    PROCEDURE FIDE_CASA_PERRITO_UPDATE_SP(
        P_ID_CASA_CUNA IN FIDE_CASA_PERRITO_TB.ID_CASA_CUNA%TYPE,
        P_ID_PERRITO   IN FIDE_CASA_PERRITO_TB.ID_PERRITO%TYPE,
        P_ID_ESTADO    IN FIDE_CASA_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CASA_PERRITO_TB DELETE LOGICO */

    PROCEDURE FIDE_CASA_PERRITO_DELETE_SP(
        P_ID_CASA_CUNA IN FIDE_CASA_PERRITO_TB.ID_CASA_CUNA%TYPE,
        P_ID_PERRITO   IN FIDE_CASA_PERRITO_TB.ID_PERRITO%TYPE
    );

    /* PROCEDURE FIDE_ADOPCION_TB INSERT */

    PROCEDURE FIDE_ADOPCION_INSERT_SP(
        P_IDENTIFICACION  IN FIDE_ADOPCION_TB.IDENTIFICACION%TYPE,
        P_ID_SOLICITUD    IN FIDE_ADOPCION_TB.ID_SOLICITUD%TYPE,
        P_FECHA_ADOPCION  IN FIDE_ADOPCION_TB.FECHA_ADOPCION%TYPE,
        P_ID_ESTADO       IN FIDE_ADOPCION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_ADOPCION_TB UPDATE */

    PROCEDURE FIDE_ADOPCION_UPDATE_SP(
        P_ID_ADOPCION     IN FIDE_ADOPCION_TB.ID_ADOPCION%TYPE,
        P_IDENTIFICACION  IN FIDE_ADOPCION_TB.IDENTIFICACION%TYPE,
        P_ID_SOLICITUD    IN FIDE_ADOPCION_TB.ID_SOLICITUD%TYPE,
        P_FECHA_ADOPCION  IN FIDE_ADOPCION_TB.FECHA_ADOPCION%TYPE,
        P_ID_ESTADO       IN FIDE_ADOPCION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_ADOPCION_TB DELETE LOGICO */

    PROCEDURE FIDE_ADOPCION_DELETE_SP(
        P_ID_ADOPCION IN FIDE_ADOPCION_TB.ID_ADOPCION%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SEGUIMIENTO INSERT */

    PROCEDURE FIDE_TIPO_SEGUIMIENTO_INSERT_SP(
        P_NOMBRE              IN FIDE_TIPO_SEGUIMIENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO           IN FIDE_TIPO_SEGUIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SEGUIMIENTO UPDATE */

    PROCEDURE FIDE_TIPO_SEGUIMIENTO_UPDATE_SP(
        P_ID_TIPO_SEGUIMIENTO IN FIDE_TIPO_SEGUIMIENTO_TB.ID_TIPO_SEGUIMIENTO%TYPE,
        P_NOMBRE              IN FIDE_TIPO_SEGUIMIENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO           IN FIDE_TIPO_SEGUIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_SEGUIMIENTO DELETE LOGICO */

    PROCEDURE FIDE_TIPO_SEGUIMIENTO_DELETE_SP(
        P_ID_TIPO_SEGUIMIENTO IN FIDE_TIPO_SEGUIMIENTO_TB.ID_TIPO_SEGUIMIENTO%TYPE
    );

    /* PROCEDURE FIDE_SEGUIMIENTO_TB INSERT */

    PROCEDURE FIDE_SEGUIMIENTO_INSERT_SP(
        P_ID_ADOPCION         IN FIDE_SEGUIMIENTO_TB.ID_ADOPCION%TYPE,
        P_ID_TIPO_SEGUIMIENTO IN FIDE_SEGUIMIENTO_TB.ID_TIPO_SEGUIMIENTO%TYPE,
        P_FECHA_INICIO        IN FIDE_SEGUIMIENTO_TB.FECHA_INICIO%TYPE,
        P_FECHA_FIN           IN FIDE_SEGUIMIENTO_TB.FECHA_FIN%TYPE,
        P_COMENTARIOS         IN FIDE_SEGUIMIENTO_TB.COMENTARIOS%TYPE,
        P_ID_ESTADO           IN FIDE_SEGUIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SEGUIMIENTO_TB UPDATE */

    PROCEDURE FIDE_SEGUIMIENTO_UPDATE_SP(
        P_ID_SEGUIMIENTO      IN FIDE_SEGUIMIENTO_TB.ID_SEGUIMIENTO%TYPE,
        P_ID_ADOPCION         IN FIDE_SEGUIMIENTO_TB.ID_ADOPCION%TYPE,
        P_ID_TIPO_SEGUIMIENTO IN FIDE_SEGUIMIENTO_TB.ID_TIPO_SEGUIMIENTO%TYPE,
        P_FECHA_INICIO        IN FIDE_SEGUIMIENTO_TB.FECHA_INICIO%TYPE,
        P_FECHA_FIN           IN FIDE_SEGUIMIENTO_TB.FECHA_FIN%TYPE,
        P_COMENTARIOS         IN FIDE_SEGUIMIENTO_TB.COMENTARIOS%TYPE,
        P_ID_ESTADO           IN FIDE_SEGUIMIENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_SEGUIMIENTO_TB DELETE LOGICO */

    PROCEDURE FIDE_SEGUIMIENTO_DELETE_SP(
        P_ID_SEGUIMIENTO IN FIDE_SEGUIMIENTO_TB.ID_SEGUIMIENTO%TYPE
    );

    /* PROCEDURE FIDE_EVIDENCIA_TB INSERT */

    PROCEDURE FIDE_EVIDENCIA_INSERT_SP(
        P_ID_SEGUIMIENTO IN FIDE_EVIDENCIA_TB.ID_SEGUIMIENTO%TYPE,
        P_IMAGEN_URL     IN FIDE_EVIDENCIA_TB.IMAGEN_URL%TYPE,
        P_COMENTARIOS    IN FIDE_EVIDENCIA_TB.COMENTARIOS%TYPE,
        P_FECHA          IN FIDE_EVIDENCIA_TB.FECHA_EVIDENCIA%TYPE,
        P_ID_ESTADO      IN FIDE_EVIDENCIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_EVIDENCIA_TB UPDATE */

    PROCEDURE FIDE_EVIDENCIA_UPDATE_SP(
        P_ID_EVIDENCIA   IN FIDE_EVIDENCIA_TB.ID_EVIDENCIA%TYPE,
        P_ID_SEGUIMIENTO IN FIDE_EVIDENCIA_TB.ID_SEGUIMIENTO%TYPE,
        P_IMAGEN_URL     IN FIDE_EVIDENCIA_TB.IMAGEN_URL%TYPE,
        P_COMENTARIOS    IN FIDE_EVIDENCIA_TB.COMENTARIOS%TYPE,
        P_FECHA          IN FIDE_EVIDENCIA_TB.FECHA_EVIDENCIA%TYPE,
        P_ID_ESTADO      IN FIDE_EVIDENCIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CAMPANIA_TB INSERT */

    PROCEDURE FIDE_CAMPANIA_INSERT_SP(
        P_NOMBRE        IN FIDE_CAMPANIA_TB.NOMBRE%TYPE,
        P_DESCRIPCION   IN FIDE_CAMPANIA_TB.DESCRIPCION%TYPE,
        P_FECHA_INICIO  IN FIDE_CAMPANIA_TB.FECHA_INICIO%TYPE,
        P_FECHA_FIN     IN FIDE_CAMPANIA_TB.FECHA_FIN%TYPE,
        P_ID_ESTADO     IN FIDE_CAMPANIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CAMPANIA_TB UPDATE */

    PROCEDURE FIDE_CAMPANIA_UPDATE_SP(
        P_ID_CAMPANIA   IN FIDE_CAMPANIA_TB.ID_CAMPANIA%TYPE,
        P_NOMBRE        IN FIDE_CAMPANIA_TB.NOMBRE%TYPE,
        P_DESCRIPCION   IN FIDE_CAMPANIA_TB.DESCRIPCION%TYPE,
        P_FECHA_INICIO  IN FIDE_CAMPANIA_TB.FECHA_INICIO%TYPE,
        P_FECHA_FIN     IN FIDE_CAMPANIA_TB.FECHA_FIN%TYPE,
        P_ID_ESTADO     IN FIDE_CAMPANIA_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_CAMPANIA_TB DELETE LOGICO */

    PROCEDURE FIDE_CAMPANIA_DELETE_SP(
        P_ID_CAMPANIA IN FIDE_CAMPANIA_TB.ID_CAMPANIA%TYPE
    );

    /* PROCEDURE FIDE_DONACION_TB INSERT */

    PROCEDURE FIDE_DONACION_INSERT_SP(
        P_IDENTIFICACION   IN FIDE_DONACION_TB.IDENTIFICACION%TYPE,
        P_ID_CAMPANIA      IN FIDE_DONACION_TB.ID_CAMPANIA%TYPE,
        P_MONTO            IN FIDE_DONACION_TB.MONTO%TYPE,
        P_FECHA_DONACION   IN FIDE_DONACION_TB.FECHA_DONACION%TYPE,
        P_MENSAJE          IN FIDE_DONACION_TB.MENSAJE%TYPE,
        P_ID_ESTADO        IN FIDE_DONACION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DONACION_TB UPDATE */

    PROCEDURE FIDE_DONACION_UPDATE_SP(
        P_ID_DONACION      IN FIDE_DONACION_TB.ID_DONACION%TYPE,
        P_IDENTIFICACION   IN FIDE_DONACION_TB.IDENTIFICACION%TYPE,
        P_ID_CAMPANIA      IN FIDE_DONACION_TB.ID_CAMPANIA%TYPE,
        P_MONTO            IN FIDE_DONACION_TB.MONTO%TYPE,
        P_FECHA_DONACION   IN FIDE_DONACION_TB.FECHA_DONACION%TYPE,
        P_MENSAJE          IN FIDE_DONACION_TB.MENSAJE%TYPE,
        P_ID_ESTADO        IN FIDE_DONACION_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DONACION_TB DELETE LOGICO */

    PROCEDURE FIDE_DONACION_DELETE_SP(
        P_ID_DONACION IN FIDE_DONACION_TB.ID_DONACION%TYPE
    );

    /* PROCEDURE FIDE_TIPO_EVENTO_TB INSERT */

    PROCEDURE FIDE_TIPO_EVENTO_INSERT_SP(
        P_NOMBRE         IN FIDE_TIPO_EVENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO      IN FIDE_TIPO_EVENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_EVENTO_TB UPDATE */

    PROCEDURE FIDE_TIPO_EVENTO_UPDATE_SP(
        P_ID_TIPO_EVENTO IN FIDE_TIPO_EVENTO_TB.ID_TIPO_EVENTO%TYPE,
        P_NOMBRE         IN FIDE_TIPO_EVENTO_TB.NOMBRE%TYPE,
        P_ID_ESTADO      IN FIDE_TIPO_EVENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_TIPO_EVENTO_TB DELETE LOGICO */

    PROCEDURE FIDE_TIPO_EVENTO_DELETE_SP(
        P_ID_TIPO_EVENTO IN FIDE_TIPO_EVENTO_TB.ID_TIPO_EVENTO%TYPE
    );

    /* PROCEDURE FIDE_EVENTO_PERRITO_TB INSERT */

    PROCEDURE FIDE_EVENTO_PERRITO_INSERT_SP(
        P_ID_PERRITO     IN FIDE_EVENTO_PERRITO_TB.ID_PERRITO%TYPE,
        P_ID_TIPO_EVENTO IN FIDE_EVENTO_PERRITO_TB.ID_TIPO_EVENTO%TYPE,
        P_FECHA_EVENTO   IN FIDE_EVENTO_PERRITO_TB.FECHA_EVENTO%TYPE,
        P_DETALLE        IN FIDE_EVENTO_PERRITO_TB.DETALLE%TYPE,
        P_TOTAL_GASTO    IN FIDE_EVENTO_PERRITO_TB.TOTAL_GASTO%TYPE,
        P_ID_ESTADO      IN FIDE_EVENTO_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_EVENTO_PERRITO_TB UPDATE */

    PROCEDURE FIDE_EVENTO_PERRITO_UPDATE_SP(
        P_ID_EVENTO      IN FIDE_EVENTO_PERRITO_TB.ID_EVENTO%TYPE,
        P_ID_PERRITO     IN FIDE_EVENTO_PERRITO_TB.ID_PERRITO%TYPE,
        P_ID_TIPO_EVENTO IN FIDE_EVENTO_PERRITO_TB.ID_TIPO_EVENTO%TYPE,
        P_FECHA_EVENTO   IN FIDE_EVENTO_PERRITO_TB.FECHA_EVENTO%TYPE,
        P_DETALLE        IN FIDE_EVENTO_PERRITO_TB.DETALLE%TYPE,
        P_TOTAL_GASTO    IN FIDE_EVENTO_PERRITO_TB.TOTAL_GASTO%TYPE,
        P_ID_ESTADO      IN FIDE_EVENTO_PERRITO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_EVENTO_PERRITO_TB DELETE LOGICO */

    PROCEDURE FIDE_EVENTO_PERRITO_DELETE_SP(
        P_ID_EVENTO IN FIDE_EVENTO_PERRITO_TB.ID_EVENTO%TYPE
    );

    /* PROCEDURE FIDE_DETALLE_EVENTO_TB INSERT */

    PROCEDURE FIDE_DETALLE_EVENTO_INSERT_SP(
        P_ID_EVENTO         IN FIDE_DETALLE_EVENTO_TB.ID_EVENTO%TYPE,
        P_COMPROBANTE_URL   IN FIDE_DETALLE_EVENTO_TB.COMPROBANTE_URL%TYPE,
        P_DESCRIPCION       IN FIDE_DETALLE_EVENTO_TB.DESCRIPCION%TYPE,
        P_MONTO             IN FIDE_DETALLE_EVENTO_TB.MONTO%TYPE,
        P_ID_ESTADO         IN FIDE_DETALLE_EVENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DETALLE_EVENTO_TB UPDATE */

    PROCEDURE FIDE_DETALLE_EVENTO_UPDATE_SP(
        P_ID_DETALLE_EVENTO IN FIDE_DETALLE_EVENTO_TB.ID_DETALLE_EVENTO%TYPE,
        P_ID_EVENTO         IN FIDE_DETALLE_EVENTO_TB.ID_EVENTO%TYPE,
        P_COMPROBANTE_URL   IN FIDE_DETALLE_EVENTO_TB.COMPROBANTE_URL%TYPE,
        P_DESCRIPCION       IN FIDE_DETALLE_EVENTO_TB.DESCRIPCION%TYPE,
        P_MONTO             IN FIDE_DETALLE_EVENTO_TB.MONTO%TYPE,
        P_ID_ESTADO         IN FIDE_DETALLE_EVENTO_TB.ID_ESTADO%TYPE
    );

    /* PROCEDURE FIDE_DETALLE_EVENTO_TB DELETE LOGICO */

    PROCEDURE FIDE_DETALLE_EVENTO_DELETE_SP(
        P_ID_DETALLE_EVENTO IN FIDE_DETALLE_EVENTO_TB.ID_DETALLE_EVENTO%TYPE
    );

END FIDE_KALO_PKG;
/
