-- TRIGGERS DE AUDITORIA Y FACTURACION

CREATE SEQUENCE FIDE_ESTADO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_USUARIO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PAIS_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_OTP_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CATEGORIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_MARCA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_MOVIMIENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CAMPANIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_MONEDA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_RAZA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_SEXO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_SOLICITUD_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_RESPUESTA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_SEGUIMIENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_TIPO_EVENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PROVINCIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CANTON_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_DISTRITO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_DIRECCION_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PRODUCTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PRODUCTO_IMAGEN_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PREGUNTA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CUENTA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CODIGO_OTP_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_REFRESH_TOKEN_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_VENTA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_DONACION_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PERRITO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PERRITO_IMAGEN_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_EVENTO_PERRITO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_DETALLE_EVENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_SOLICITUD_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_RESPUESTA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_CASA_CUNA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_ADOPCION_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_SEGUIMIENTO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_EVIDENCIA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_FACTURA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_PAGO_PAYPAL_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_INVENTARIO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE FIDE_MOVIMIENTO_INVENTARIO_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE FUNCTION FIDE_ALPHA_NUMERIC_SEQ_FN
RETURN VARCHAR2 AS
    V_FECHA VARCHAR2(10);
    V_LETRA CHAR(1);
    V_VALOR VARCHAR2(30);
BEGIN
    V_FECHA := TO_CHAR(SYSDATE, 'DDMMYYY');
    V_LETRA := CHR(65 + TRUNC(DBMS_RANDOM.VALUE(0, 26)));
    V_VALOR := V_FECHA || '-' || LPAD(FIDE_FACTURA_SEQ.NEXTVAL, 7, '0') || '-' || V_LETRA;

    RETURN V_VALOR;
END FIDE_ALPHA_NUMERIC_SEQ_FN;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO IS NULL THEN
        :NEW.ID_ESTADO := FIDE_ESTADO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
END FIDE_ESTADO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_ESTADO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_USUARIO IS NULL THEN
        :NEW.ID_TIPO_USUARIO := FIDE_TIPO_USUARIO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_USUARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_USUARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_USUARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_INSERT_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PAIS IS NULL THEN
        :NEW.ID_PAIS := FIDE_PAIS_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PAIS_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PAIS_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_DELETE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PAIS_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_OTP IS NULL THEN
        :NEW.ID_TIPO_OTP := FIDE_TIPO_OTP_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_OTP_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_OTP_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_OTP_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CATEGORIA IS NULL THEN
        :NEW.ID_CATEGORIA := FIDE_CATEGORIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CATEGORIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CATEGORIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_DELETE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CATEGORIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_INSERT_TRG
BEFORE INSERT ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_MARCA IS NULL THEN
        :NEW.ID_MARCA := FIDE_MARCA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MARCA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_UPDATE_TRG
BEFORE UPDATE ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MARCA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_DELETE_TRG
BEFORE UPDATE ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MARCA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_MOVIMIENTO IS NULL THEN
        :NEW.ID_TIPO_MOVIMIENTO := FIDE_TIPO_MOVIMIENTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_MOVIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_MOVIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_MOVIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_INSERT_TRG
BEFORE INSERT ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CAMPANIA IS NULL THEN
        :NEW.ID_CAMPANIA := FIDE_CAMPANIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CAMPANIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CAMPANIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_DELETE_TRG
BEFORE UPDATE ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CAMPANIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_INSERT_TRG
BEFORE INSERT ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_MONEDA IS NULL THEN
        :NEW.ID_MONEDA := FIDE_MONEDA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MONEDA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_UPDATE_TRG
BEFORE UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MONEDA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_DELETE_TRG
BEFORE UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MONEDA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_INSERT_TRG
BEFORE INSERT ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_RAZA IS NULL THEN
        :NEW.ID_RAZA := FIDE_RAZA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_RAZA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_UPDATE_TRG
BEFORE UPDATE ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_RAZA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_DELETE_TRG
BEFORE UPDATE ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_RAZA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_INSERT_TRG
BEFORE INSERT ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_SEXO IS NULL THEN
        :NEW.ID_SEXO := FIDE_SEXO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_SEXO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SEXO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_DELETE_TRG
BEFORE UPDATE ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SEXO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_SOLICITUD IS NULL THEN
        :NEW.ID_TIPO_SOLICITUD := FIDE_TIPO_SOLICITUD_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_SOLICITUD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_SOLICITUD_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_SOLICITUD_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_RESPUESTA IS NULL THEN
        :NEW.ID_TIPO_RESPUESTA := FIDE_TIPO_RESPUESTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_RESPUESTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_RESPUESTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_RESPUESTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_SEGUIMIENTO IS NULL THEN
        :NEW.ID_TIPO_SEGUIMIENTO := FIDE_TIPO_SEGUIMIENTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_SEGUIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_SEGUIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_SEGUIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_EVENTO IS NULL THEN
        :NEW.ID_TIPO_EVENTO := FIDE_TIPO_EVENTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_EVENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_EVENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_EVENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROVINCIA IS NULL THEN
        :NEW.ID_PROVINCIA := FIDE_PROVINCIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PROVINCIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PROVINCIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_DELETE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PROVINCIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_INSERT_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CANTON IS NULL THEN
        :NEW.ID_CANTON := FIDE_CANTON_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CANTON_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CANTON_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_DELETE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CANTON_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DISTRITO IS NULL THEN
        :NEW.ID_DISTRITO := FIDE_DISTRITO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DISTRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DISTRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DISTRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DIRECCION IS NULL THEN
        :NEW.ID_DIRECCION := FIDE_DIRECCION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DIRECCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DIRECCION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_DELETE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DIRECCION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_INSERT_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN
        :NEW.ID_PRODUCTO := FIDE_PRODUCTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PRODUCTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PRODUCTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_DELETE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PRODUCTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_IMAGEN_INSERT_TRG
BEFORE INSERT ON FIDE_PRODUCTO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_IMAGEN IS NULL THEN
        :NEW.ID_IMAGEN := FIDE_PRODUCTO_IMAGEN_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PRODUCTO_IMAGEN_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_IMAGEN_UPDATE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PRODUCTO_IMAGEN_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_IMAGEN_DELETE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PRODUCTO_IMAGEN_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_INSERT_TRG
BEFORE INSERT ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PREGUNTA IS NULL THEN
        :NEW.ID_PREGUNTA := FIDE_PREGUNTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END FIDE_PREGUNTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PREGUNTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_DELETE_TRG
BEFORE UPDATE ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PREGUNTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_USUARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_USUARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_USUARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_INSERT_TRG
BEFORE INSERT ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CORREO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CORREO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_DELETE_TRG
BEFORE UPDATE ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CORREO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_INSERT_TRG
BEFORE INSERT ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TELEFONO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TELEFONO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_DELETE_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TELEFONO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_INSERT_TRG
BEFORE INSERT ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CUENTA IS NULL THEN
        :NEW.ID_CUENTA := FIDE_CUENTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CUENTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CUENTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_DELETE_TRG
BEFORE UPDATE ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CUENTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_INSERT_TRG
BEFORE INSERT ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CODIGO_OTP IS NULL THEN
        :NEW.ID_CODIGO_OTP := FIDE_CODIGO_OTP_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CODIGO_OTP_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_UPDATE_TRG
BEFORE UPDATE ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CODIGO_OTP_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_DELETE_TRG
BEFORE UPDATE ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CODIGO_OTP_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_INSERT_TRG
BEFORE INSERT ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_REFRESH_TOKEN IS NULL THEN
        :NEW.ID_REFRESH_TOKEN := FIDE_REFRESH_TOKEN_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_REFRESH_TOKEN_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_UPDATE_TRG
BEFORE UPDATE ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_REFRESH_TOKEN_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_DELETE_TRG
BEFORE UPDATE ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_REFRESH_TOKEN_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_VENTA IS NULL THEN
        :NEW.ID_VENTA := FIDE_VENTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_INSERT_TRG
BEFORE INSERT ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DONACION IS NULL THEN
        :NEW.ID_DONACION := FIDE_DONACION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DONACION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DONACION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_DELETE_TRG
BEFORE UPDATE ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DONACION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PERRITO IS NULL THEN
        :NEW.ID_PERRITO := FIDE_PERRITO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGEN_INSERT_TRG
BEFORE INSERT ON FIDE_PERRITO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_IMAGEN IS NULL THEN
        :NEW.ID_IMAGEN := FIDE_PERRITO_IMAGEN_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PERRITO_IMAGEN_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGEN_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERRITO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PERRITO_IMAGEN_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGEN_DELETE_TRG
BEFORE UPDATE ON FIDE_PERRITO_IMAGEN_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PERRITO_IMAGEN_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_EVENTO IS NULL THEN
        :NEW.ID_EVENTO := FIDE_EVENTO_PERRITO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_EVENTO_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_EVENTO_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_EVENTO_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_DETALLE_EVENTO IS NULL THEN
        :NEW.ID_DETALLE_EVENTO := FIDE_DETALLE_EVENTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DETALLE_EVENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DETALLE_EVENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DETALLE_EVENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_INSERT_TRG
BEFORE INSERT ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_SOLICITUD IS NULL THEN
        :NEW.ID_SOLICITUD := FIDE_SOLICITUD_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END FIDE_SOLICITUD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_UPDATE_TRG
BEFORE UPDATE ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SOLICITUD_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_DELETE_TRG
BEFORE UPDATE ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SOLICITUD_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_PREGUNTA_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_SOLICITUD_PREGUNTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END FIDE_TIPO_SOLICITUD_PREGUNTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_PREGUNTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_SOLICITUD_PREGUNTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_PREGUNTA_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_SOLICITUD_PREGUNTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_INSERT_TRG
BEFORE INSERT ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_RESPUESTA IS NULL THEN
        :NEW.ID_RESPUESTA := FIDE_RESPUESTA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END FIDE_RESPUESTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_RESPUESTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_DELETE_TRG
BEFORE UPDATE ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_RESPUESTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_INSERT_TRG
BEFORE INSERT ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_CASA_CUNA IS NULL THEN
        :NEW.ID_CASA_CUNA := FIDE_CASA_CUNA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CASA_CUNA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CASA_CUNA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_DELETE_TRG
BEFORE UPDATE ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CASA_CUNA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_INSERT_TRG
BEFORE INSERT ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_ADOPCION IS NULL THEN
        :NEW.ID_ADOPCION := FIDE_ADOPCION_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := NVL(:NEW.ID_ESTADO, 1);
END FIDE_ADOPCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_ADOPCION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_DELETE_TRG
BEFORE UPDATE ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_ADOPCION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_SEGUIMIENTO IS NULL THEN
        :NEW.ID_SEGUIMIENTO := FIDE_SEGUIMIENTO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_SEGUIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SEGUIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SEGUIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_INSERT_TRG
BEFORE INSERT ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_EVIDENCIA IS NULL THEN
        :NEW.ID_EVIDENCIA := FIDE_EVIDENCIA_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_EVIDENCIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_EVIDENCIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_DELETE_TRG
BEFORE UPDATE ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_EVIDENCIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CASA_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CASA_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CASA_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_FACTURA IS NULL THEN
        :NEW.ID_FACTURA := FIDE_ALPHA_NUMERIC_SEQ_FN();
    END IF;
    IF :NEW.TASA_IMPUESTO_APLICADA IS NULL THEN
        :NEW.TASA_IMPUESTO_APLICADA := 0.13;
    END IF;
    :NEW.SUBTOTAL := NVL(:NEW.SUBTOTAL, 0);
    :NEW.IMPUESTO := NVL(:NEW.IMPUESTO, 0);
    :NEW.TOTAL := NVL(:NEW.TOTAL, 0);
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_FACTURA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_FACTURA_INSERT_TRG;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_VENTA_FACTURA_CALC_INSERT_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_VENTA_FACTURA_CALC_UPDATE_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_VENTA_FACTURA_CALC_DELETE_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_CALC_TRG
FOR INSERT OR UPDATE OF ID_VENTA, ID_FACTURA, ID_ESTADO ON FIDE_VENTA_FACTURA_TB
COMPOUND TRIGGER
    TYPE T_FACTURA_IDS IS TABLE OF FIDE_FACTURA_TB.ID_FACTURA%TYPE INDEX BY PLS_INTEGER;
    G_FACTURA_IDS T_FACTURA_IDS;
    G_FACTURA_COUNT PLS_INTEGER := 0;

    PROCEDURE ADD_FACTURA_ID(P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE)
    IS
    BEGIN
        IF P_ID_FACTURA IS NULL THEN
            RETURN;
        END IF;

        FOR I IN 1 .. G_FACTURA_COUNT LOOP
            IF G_FACTURA_IDS(I) = P_ID_FACTURA THEN
                RETURN;
            END IF;
        END LOOP;

        G_FACTURA_COUNT := G_FACTURA_COUNT + 1;
        G_FACTURA_IDS(G_FACTURA_COUNT) := P_ID_FACTURA;
    END ADD_FACTURA_ID;

    AFTER EACH ROW
    IS
    BEGIN
        ADD_FACTURA_ID(:NEW.ID_FACTURA);

        IF UPDATING('ID_FACTURA') AND :OLD.ID_FACTURA <> :NEW.ID_FACTURA THEN
            ADD_FACTURA_ID(:OLD.ID_FACTURA);
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT
    IS
    BEGIN
        FOR I IN 1 .. G_FACTURA_COUNT LOOP
            FIDE_KALO_PKG.FIDE_RECALCULAR_FACTURA_POR_ID_SP(G_FACTURA_IDS(I));
        END LOOP;
    END AFTER STATEMENT;
END FIDE_VENTA_FACTURA_CALC_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DONACION_FACTURA_INSERT_TRG;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_DONACION_FACTURA_CALC_INSERT_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_DONACION_FACTURA_CALC_UPDATE_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER FIDE_DONACION_FACTURA_CALC_DELETE_TRG';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -4080 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_CALC_TRG
FOR INSERT OR UPDATE OF ID_DONACION, ID_FACTURA, ID_ESTADO ON FIDE_DONACION_FACTURA_TB
COMPOUND TRIGGER
    TYPE T_FACTURA_IDS IS TABLE OF FIDE_FACTURA_TB.ID_FACTURA%TYPE INDEX BY PLS_INTEGER;
    G_FACTURA_IDS T_FACTURA_IDS;
    G_FACTURA_COUNT PLS_INTEGER := 0;

    PROCEDURE ADD_FACTURA_ID(P_ID_FACTURA IN FIDE_FACTURA_TB.ID_FACTURA%TYPE)
    IS
    BEGIN
        IF P_ID_FACTURA IS NULL THEN
            RETURN;
        END IF;

        FOR I IN 1 .. G_FACTURA_COUNT LOOP
            IF G_FACTURA_IDS(I) = P_ID_FACTURA THEN
                RETURN;
            END IF;
        END LOOP;

        G_FACTURA_COUNT := G_FACTURA_COUNT + 1;
        G_FACTURA_IDS(G_FACTURA_COUNT) := P_ID_FACTURA;
    END ADD_FACTURA_ID;

    AFTER EACH ROW
    IS
    BEGIN
        ADD_FACTURA_ID(:NEW.ID_FACTURA);

        IF UPDATING('ID_FACTURA') AND :OLD.ID_FACTURA <> :NEW.ID_FACTURA THEN
            ADD_FACTURA_ID(:OLD.ID_FACTURA);
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT
    IS
    BEGIN
        FOR I IN 1 .. G_FACTURA_COUNT LOOP
            FIDE_KALO_PKG.FIDE_RECALCULAR_FACTURA_POR_ID_SP(G_FACTURA_IDS(I));
        END LOOP;
    END AFTER STATEMENT;
END FIDE_DONACION_FACTURA_CALC_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DONACION_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DONACION_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_INSERT_TRG
BEFORE INSERT ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_PAGO IS NULL THEN
        :NEW.ID_PAGO := FIDE_PAGO_PAYPAL_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PAGO_PAYPAL_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PAGO_PAYPAL_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_DELETE_TRG
BEFORE UPDATE ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PAGO_PAYPAL_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_INSERT_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_INVENTARIO IS NULL THEN
        :NEW.ID_INVENTARIO := FIDE_INVENTARIO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_INVENTARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_INVENTARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_INVENTARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_INSERT_TRG
BEFORE INSERT ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF :NEW.ID_MOVIMIENTO IS NULL THEN
        :NEW.ID_MOVIMIENTO := FIDE_MOVIMIENTO_INVENTARIO_SEQ.NEXTVAL;
    END IF;
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MOVIMIENTO_INVENTARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MOVIMIENTO_INVENTARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MOVIMIENTO_INVENTARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_PRODUCTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_PRODUCTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_PRODUCTO_DELETE_TRG;
/
