-- TRIGGERS DE AUDITORIA Y FACTURACION

CREATE SEQUENCE FIDE_FACTURA_SEQ
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE FUNCTION FIDE_ALPHA_NUMERIC_SEQ_FN
RETURN VARCHAR2 AS
    V_FECHA VARCHAR2(10);
    V_LETRA CHAR(1);
    V_VALOR VARCHAR2(30);
BEGIN
    V_FECHA := TO_CHAR(SYSDATE, 'DDMMYYY');
    V_LETRA := CHR(65 + TRUNC(DBMS_RANDOM.VALUE(0, 26)));
    V_VALOR := V_FECHA || '-' || LPAD(FIDE_FACTURA_SEQ.NEXTVAL, 7, '0') || '-' || V_LETRA;

    RETURN V_VALOR;
END FIDE_ALPHA_NUMERIC_SEQ_FN;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_INSERT_TRG
BEFORE INSERT ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_ESTADO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ESTADO_UPDATE_TRG
BEFORE UPDATE ON FIDE_ESTADO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_ESTADO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_USUARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_USUARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_USUARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_USUARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_INSERT_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PAIS_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PAIS_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAIS_DELETE_TRG
BEFORE UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PAIS_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_OTP_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_OTP_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_OTP_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_OTP_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_OTP_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_INSERT_TRG
BEFORE INSERT ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CATEGORIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CATEGORIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CATEGORIA_DELETE_TRG
BEFORE UPDATE ON FIDE_CATEGORIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CATEGORIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_INSERT_TRG
BEFORE INSERT ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MARCA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_UPDATE_TRG
BEFORE UPDATE ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MARCA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MARCA_DELETE_TRG
BEFORE UPDATE ON FIDE_MARCA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MARCA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_MOVIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_MOVIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MOVIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_MOVIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_MOVIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_INSERT_TRG
BEFORE INSERT ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CAMPANIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CAMPANIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CAMPANIA_DELETE_TRG
BEFORE UPDATE ON FIDE_CAMPANIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CAMPANIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_INSERT_TRG
BEFORE INSERT ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MONEDA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_UPDATE_TRG
BEFORE UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MONEDA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_DELETE_TRG
BEFORE UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MONEDA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_INSERT_TRG
BEFORE INSERT ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_RAZA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_UPDATE_TRG
BEFORE UPDATE ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_RAZA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RAZA_DELETE_TRG
BEFORE UPDATE ON FIDE_RAZA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_RAZA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_INSERT_TRG
BEFORE INSERT ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_SEXO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SEXO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEXO_DELETE_TRG
BEFORE UPDATE ON FIDE_SEXO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SEXO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_SOLICITUD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_SOLICITUD_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SOLICITUD_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_SOLICITUD_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_RESPUESTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_RESPUESTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_RESPUESTA_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_RESPUESTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_SEGUIMIENTO
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_SEGUIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_SEGUIMIENTO
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_SEGUIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_SEGUIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_SEGUIMIENTO
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_SEGUIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_INSERT_TRG
BEFORE INSERT ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TIPO_EVENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TIPO_EVENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TIPO_EVENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_TIPO_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TIPO_EVENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_INSERT_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PROVINCIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PROVINCIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_DELETE_TRG
BEFORE UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PROVINCIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_INSERT_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CANTON_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_UPDATE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CANTON_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CANTON_DELETE_TRG
BEFORE UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CANTON_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_INSERT_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DISTRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DISTRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DISTRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_INSERT_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DIRECCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DIRECCION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_DELETE_TRG
BEFORE UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DIRECCION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_INSERT_TRG
BEFORE INSERT ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PRODUCTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PRODUCTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PRODUCTO_DELETE_TRG
BEFORE UPDATE ON FIDE_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PRODUCTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_INSERT_TRG
BEFORE INSERT ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PREGUNTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PREGUNTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PREGUNTA_DELETE_TRG
BEFORE UPDATE ON FIDE_PREGUNTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PREGUNTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_INSERT_TRG
BEFORE INSERT ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_USUARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_USUARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_USUARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_USUARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_USUARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_INSERT_TRG
BEFORE INSERT ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CORREO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CORREO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CORREO_DELETE_TRG
BEFORE UPDATE ON FIDE_CORREO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CORREO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_INSERT_TRG
BEFORE INSERT ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_TELEFONO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_UPDATE_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_TELEFONO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_TELEFONO_DELETE_TRG
BEFORE UPDATE ON FIDE_TELEFONO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_TELEFONO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_INSERT_TRG
BEFORE INSERT ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CUENTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CUENTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CUENTA_DELETE_TRG
BEFORE UPDATE ON FIDE_CUENTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CUENTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_INSERT_TRG
BEFORE INSERT ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CODIGO_OTP_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_UPDATE_TRG
BEFORE UPDATE ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CODIGO_OTP_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CODIGO_OTP_DELETE_TRG
BEFORE UPDATE ON FIDE_CODIGO_OTP_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CODIGO_OTP_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_INSERT_TRG
BEFORE INSERT ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_REFRESH_TOKEN_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_UPDATE_TRG
BEFORE UPDATE ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_REFRESH_TOKEN_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_REFRESH_TOKEN_DELETE_TRG
BEFORE UPDATE ON FIDE_REFRESH_TOKEN_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_REFRESH_TOKEN_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_INSERT_TRG
BEFORE INSERT ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DONACION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_UPDATE_TRG
BEFORE UPDATE ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DONACION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_DELETE_TRG
BEFORE UPDATE ON FIDE_DONACION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DONACION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGE_INSERT_TRG
BEFORE INSERT ON FIDE_PERRITO_IMAGE_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PERRITO_IMAGE_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGE_UPDATE_TRG
BEFORE UPDATE ON FIDE_PERRITO_IMAGE_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PERRITO_IMAGE_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PERRITO_IMAGE_DELETE_TRG
BEFORE UPDATE ON FIDE_PERRITO_IMAGE_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PERRITO_IMAGE_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_EVENTO_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_EVENTO_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVENTO_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_EVENTO_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_EVENTO_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_INSERT_TRG
BEFORE INSERT ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DETALLE_EVENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DETALLE_EVENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DETALLE_EVENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_DETALLE_EVENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DETALLE_EVENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_INSERT_TRG
BEFORE INSERT ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_SOLICITUD_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_UPDATE_TRG
BEFORE UPDATE ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SOLICITUD_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SOLICITUD_DELETE_TRG
BEFORE UPDATE ON FIDE_SOLICITUD_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SOLICITUD_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_INSERT_TRG
BEFORE INSERT ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_RESPUESTA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_UPDATE_TRG
BEFORE UPDATE ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_RESPUESTA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_RESPUESTA_DELETE_TRG
BEFORE UPDATE ON FIDE_RESPUESTA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_RESPUESTA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_INSERT_TRG
BEFORE INSERT ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CASA_CUNA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_UPDATE_TRG
BEFORE UPDATE ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CASA_CUNA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_CUNA_DELETE_TRG
BEFORE UPDATE ON FIDE_CASA_CUNA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CASA_CUNA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_INSERT_TRG
BEFORE INSERT ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_ADOPCION_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_UPDATE_TRG
BEFORE UPDATE ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_ADOPCION_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_ADOPCION_DELETE_TRG
BEFORE UPDATE ON FIDE_ADOPCION_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_ADOPCION_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_INSERT_TRG
BEFORE INSERT ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_SEGUIMIENTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_SEGUIMIENTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_SEGUIMIENTO_DELETE_TRG
BEFORE UPDATE ON FIDE_SEGUIMIENTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_SEGUIMIENTO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_INSERT_TRG
BEFORE INSERT ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_EVIDENCIA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_UPDATE_TRG
BEFORE UPDATE ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_EVIDENCIA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_EVIDENCIA_DELETE_TRG
BEFORE UPDATE ON FIDE_EVIDENCIA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_EVIDENCIA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_INSERT_TRG
BEFORE INSERT ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_CASA_PERRITO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_UPDATE_TRG
BEFORE UPDATE ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_CASA_PERRITO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_CASA_PERRITO_DELETE_TRG
BEFORE UPDATE ON FIDE_CASA_PERRITO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_CASA_PERRITO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.ID_FACTURA := FIDE_ALPHA_NUMERIC_SEQ_FN();
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_FACTURA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_FACTURA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_INSERT_TRG
BEFORE INSERT ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_DONACION_FACTURA_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_UPDATE_TRG
BEFORE UPDATE ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_DONACION_FACTURA_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_DONACION_FACTURA_DELETE_TRG
BEFORE UPDATE ON FIDE_DONACION_FACTURA_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_DONACION_FACTURA_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_INSERT_TRG
BEFORE INSERT ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_PAGO_PAYPAL_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_UPDATE_TRG
BEFORE UPDATE ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_PAGO_PAYPAL_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_PAGO_PAYPAL_DELETE_TRG
BEFORE UPDATE ON FIDE_PAGO_PAYPAL_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_PAGO_PAYPAL_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_INSERT_TRG
BEFORE INSERT ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_INVENTARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_INVENTARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_INVENTARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_INVENTARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_INSERT_TRG
BEFORE INSERT ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_MOVIMIENTO_INVENTARIO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_UPDATE_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_MOVIMIENTO_INVENTARIO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_MOVIMIENTO_INVENTARIO_DELETE_TRG
BEFORE UPDATE ON FIDE_MOVIMIENTO_INVENTARIO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_MOVIMIENTO_INVENTARIO_DELETE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_INSERT_TRG
BEFORE INSERT ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    :NEW.FECHA_CREACION := SYSTIMESTAMP;
    :NEW.CREADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
    :NEW.ACCION := 'INSERT';
    :NEW.ID_ESTADO := 1;
END FIDE_VENTA_PRODUCTO_INSERT_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_UPDATE_TRG
BEFORE UPDATE ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NOT (NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2) THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ACCION := 'UPDATE';
    END IF;
END FIDE_VENTA_PRODUCTO_UPDATE_TRG;
/

CREATE OR REPLACE TRIGGER FIDE_VENTA_PRODUCTO_DELETE_TRG
BEFORE UPDATE ON FIDE_VENTA_PRODUCTO_TB
FOR EACH ROW
BEGIN
    IF NVL(:NEW.ID_ESTADO, -1) = 2 AND NVL(:OLD.ID_ESTADO, -1) <> 2 THEN
        :NEW.FECHA_MODIFICACION := SYSTIMESTAMP;
        :NEW.MODIFICADO_POR := SYS_CONTEXT('USERENV', 'SESSION_USER');
        :NEW.ID_ESTADO := 2;
        :NEW.ACCION := 'DELETE';
    END IF;
END FIDE_VENTA_PRODUCTO_DELETE_TRG;
/

