const express = require('express');

const router = express.Router();

router.use('/auth', require('./userRoutes'));
router.use('/catalogs', require('./catalogRoutes'));
router.use('/locations', require('./locationRoutes'));
router.use('/countries', require('./countryRoutes'));
router.use('/provinces', require('./provinceRoutes'));
router.use('/cantons', require('./cantonRoutes'));
router.use('/districts', require('./districtRoutes'));
router.use('/addresses', require('./addressRoutes'));
router.use('/states', require('./stateRoutes'));
router.use('/otp-types', require('./otpTypeRoutes'));
router.use('/categories', require('./categoryRoutes'));
router.use('/brands', require('./brandRoutes'));
router.use('/movement-types', require('./movementTypeRoutes'));
router.use('/products', require('./productRoutes'));
router.use('/product-images', require('./productImageRoutes'));
router.use('/inventories', require('./inventoryRoutes'));
router.use('/inventory-movements', require('./inventoryMovementRoutes'));
router.use('/sales', require('./saleRoutes'));
router.use('/sale-products', require('./saleProductRoutes'));
router.use('/sale-invoices', require('./saleInvoiceRoutes'));
router.use('/invoices', require('./invoiceRoutes'));
router.use('/paypal-payments', require('./paypalPaymentRoutes'));
router.use('/currencies', require('./currencyRoutes'));
router.use('/breeds', require('./breedRoutes'));
router.use('/sexes', require('./sexRoutes'));
router.use('/dogs', require('./dogRoutes'));
router.use('/adoptions', require('./adoptionRoutes'));
router.use('/follow-ups', require('./followUpRoutes'));
router.use('/dog-images', require('./dogImageRoutes'));
router.use('/dog-events', require('./dogEventRoutes'));
router.use('/event-details', require('./eventDetailRoutes'));
router.use('/foster-homes', require('./fosterHomeRoutes'));
router.use('/house-dogs', require('./houseDogRoutes'));
router.use('/request-types', require('./requestTypeRoutes'));
router.use('/requests', require('./requestRoutes'));
router.use('/request-questions', require('./requestQuestionRoutes'));
router.use('/responses', require('./responseRoutes'));
router.use('/response-types', require('./responseTypeRoutes'));
router.use('/tracking-types', require('./trackingTypeRoutes'));
router.use('/event-types', require('./eventTypeRoutes'));
router.use('/questions', require('./questionRoutes'));
router.use('/user-types', require('./userTypeRoutes'));
router.use('/emails', require('./emailRoutes'));
router.use('/phones', require('./phoneRoutes'));
router.use('/accounts', require('./accountRoutes'));
router.use('/otp-codes', require('./otpRoutes'));
router.use('/refresh-tokens', require('./refreshTokenRoutes'));

module.exports = router;
